// Generated by scripts/generate-web-api.mjs; do not edit.
// Source SHA-256: 5aff85bcb6b6cf5d76f4802b47297cd5e48f62f975f12fe8594dd57c549e0791
// String bounds and cross-field/conditional constraints are enforced by the decoder.

export type Id = (string);

export type Sha256 = (string);

export type Uint64 = (string);

export type Address = (string);

export type Instant = (string);

export type ObjectId = (string);

export type Version = Id;

export type Cursor = Id;

export type Binding = ({ "jobId": Id; "runId": ((Id | (null))); "revisionId": ((Id | (null))); });

export type Acceptance = "not-evaluated" | "accepted" | "rejected" | "unknown";

export type RunState = "queued" | "running" | "cancelling" | "completed" | "failed" | "cancelled" | "interrupted";

export type Workflow = "explore" | "reconstruct" | "build" | "validate" | "repair";

export type RequestId = Id;

export type Limits = ({ "requestDeadlineMs": Uint64; "uploadDeadlineMs": Uint64; "downloadIdleMs": Uint64; "maxJsonBytes": Uint64; "maxUploadBytes": Uint64; "maxSourceChunkBytes": Uint64; "maxLogChunkBytes": Uint64; "maxEventCount": Uint64; "maxEventBytes": Uint64; "terminalEventRetentionMs": Uint64; "defaultPageLimit": (number); "maxPageLimit": (number); });

export type Capability = ({ "id": Id; "state": "supported" | "unavailable" | "unsupported" | "unknown"; "reasonCode": ((Id | (null))); "message": (((string) | (null))); "workflows": (Array<Workflow>); "agentContractVersion": (((number) | (null))); "limits": ((ExecutionLimits | (null))); });

export type Bootstrap = ({ "apiVersions": (Array<(number)>); "applicationBuildId": Id; "uiBuildId": Id; "basePath": (string); "readiness": "ready" | "degraded" | "draining" | "unavailable"; "sessionExpiresAt": Instant; "capabilities": (Array<Capability>); "limits": Limits; "runtime": Runtime; "csrfToken": (string); });

export type Session = ({ "csrfToken": (string); "expiresAt": Instant; });

export type Binary = ({ "format": (string); "endianness": "little" | "big"; "objectType": (string); "machine": (string); "osAbi": (string); "entryPoint": Address; });

export type Job = ({ "jobId": Id; "displayFilename": (string); "status": "uploaded" | "queued" | "running" | "completed" | "failed" | "cancelled" | "interrupted" | "unknown"; "createdAt": Instant; "updatedAt": Instant; "sizeBytes": Uint64; "binary": Binary; "version": Version; "latestRunId": ((Id | (null))); "acceptedRevisionId": ((Id | (null))); });

export type Page = ({ "nextCursor": ((Cursor | (null))); "snapshotVersion": Version; "limit": (number); });

export type Jobs = ({ "items": (Array<Job>); "page": Page; });

export type ExecutionLimits = ({ "wallClockMs": Uint64; "idleMs": Uint64; "maxOutputBytes": Uint64; "maxToolCalls": Uint64; });

export type Usage = ({ "inputTokens": ((Uint64 | (null))); "outputTokens": ((Uint64 | (null))); "cachedInputTokens": ((Uint64 | (null))); "toolCalls": ((Uint64 | (null))); "wallClockMs": ((Uint64 | (null))); });

export type Run = ({ "runId": Id; "jobId": Id; "workflow": Workflow; "state": RunState; "version": Version; "createdAt": Instant; "startedAt": ((Instant | (null))); "endedAt": ((Instant | (null))); "previousRunId": ((Id | (null))); "inputRevisionId": ((Id | (null))); "resultRevisionId": ((Id | (null))); "acceptance": Acceptance; "harnessCapabilityId": ((Id | (null))); "terminalReason": (("COMPLETED" | "NO_CHANGES" | "REFUSED" | "CANCELLED" | "LIMIT_EXHAUSTED" | "FAILED" | "PROCESS_INTERRUPTED" | (null))); "usage": ((Usage | (null))); "limits": ExecutionLimits; });

export type Artifact = ({ "artifactId": Id; "binding": Binding; "displayName": (string); "mediaType": (string); "sizeBytes": Uint64; "sha256": Sha256; "contentHref": (string); "role": "raw-evidence" | "sanitized-derivative" | "source" | "archive"; "derivedFromArtifactId": ((Id | (null))); });

export type Revision = ({ "revisionId": Id; "jobId": Id; "runId": ((Id | (null))); "sourceSha256": Sha256; "parentRevisionId": ((Id | (null))); "graphNodeId": ((Id | (null))); "graphStatus": (("ROOT" | "ACCEPTED" | "REJECTED" | (null))); "acceptance": Acceptance; "acceptanceArtifactId": ((Id | (null))); "publicationMode": "release" | "test-only" | "unknown"; });

export type ExplorationSummary = ({ "candidateCount": Uint64; "expandedOutputSignatures": Uint64; "confidence": ({ "score": (number); "inputCount": Uint64; "sourceCount": Uint64; "outputSignatureCount": Uint64; "newOutputSignatureCount": Uint64; "sandboxed": (boolean); "networkIsolated": (boolean); }); });

export type ValidationSummary = ({ "result": "passed" | "failed" | "unknown"; "casesCompared": Uint64; "sourceSha256": Sha256; });

export type Report = ({ "reportId": Id; "binding": Binding; "reportType": "exploration" | "revision-validation" | "unknown"; "adapterVersion": (number); "producerSchemaVersion": (((number) | (null))); "state": "available" | "partial" | "missing" | "unsupported" | "unknown" | "invalid" | "incompatible"; "authority": "observations" | "canonical-validation" | "canonical-revision-graph" | "derived-presentation" | "unknown"; "sourceArtifact": ((Artifact | (null))); "acceptance": Acceptance; "acceptanceArtifactId": ((Id | (null))); "limitations": (Array<(string)>); "summary": ((((ExplorationSummary | ValidationSummary)) | (null))); });

export type EventBase = ({ "apiVersion": 1; "kind": "event"; "type": "agent.message" | "run.state" | "evidence.available" | "retention.gap" | "workflow.observation"; "jobId": Id; "runId": Id; "cursor": ((Cursor | (null))); "sequence": ((Uint64 | (null))); "occurredAt": Instant; "originRequestId": ((RequestId | (null))); "agentInvocationId": ((Id | (null))); "agentSequence": ((Uint64 | (null))); "payload": (Record<string, unknown>); });

export type WebEvent = ((({ "type"?: "agent.message"; "payload"?: ({ "messageId": Id; "role": "ASSISTANT" | "USER" | "SYSTEM"; "textDelta": (string); "completed": (boolean); }); "agentInvocationId"?: Id; "agentSequence"?: Uint64; "cursor"?: Cursor; "sequence"?: Uint64; }) | ({ "type"?: "run.state"; "payload"?: ({ "state": RunState; "version": Version; "acceptance": Acceptance; }); "agentInvocationId"?: (null); "agentSequence"?: (null); "cursor"?: Cursor; "sequence"?: Uint64; }) | ({ "type"?: "evidence.available"; "payload"?: ({ "artifactId": Id; "revisionId": ((Id | (null))); }); "agentInvocationId"?: (null); "agentSequence"?: (null); "cursor"?: Cursor; "sequence"?: Uint64; }) | ({ "type"?: "retention.gap"; "payload"?: ({ "requestedCursor": Cursor; "oldestCursor": ((Cursor | (null))); "latestCursor": ((Cursor | (null))); "snapshotHref": (string); }); "agentInvocationId"?: (null); "agentSequence"?: (null); "cursor"?: (null); "sequence"?: (null); }) | ({ "type"?: "workflow.observation"; "payload"?: ProgressObservation; "cursor"?: Cursor; "sequence"?: Uint64; "agentInvocationId"?: (null); }))) & (EventBase);

export type Snapshot = ({ "run": Run; "throughCursor": ((Cursor | (null))); "throughSequence": ((Uint64 | (null))); "oldestCursor": ((Cursor | (null))); });

export type Events = ({ "items": (Array<WebEvent>); "nextCursor": ((Cursor | (null))); "hasMore": (boolean); });

export type GitRef = ({ "refId": Id; "displayName": (string); "objectId": ((ObjectId | (null))); "version": Version; });

export type GitMapping = ({ "repositoryId": Id; "objectId": ObjectId; "revisionId": Id; "sourceSha256": Sha256; "archiveArtifactId": ((Id | (null))); "acceptance": Acceptance; "acceptanceArtifactId": ((Id | (null))); });

export type GitWorkspace = ({ "repositoryId": Id; "worktreeId": Id; "repositoryVersion": Version; "worktreeVersion": Version; "objectFormat": "sha1" | "sha256" | "unknown"; "headObjectId": ((ObjectId | (null))); "headRefId": ((Id | (null))); "candidateRevisionId": ((Id | (null))); "dirty": (boolean); "refs": (Array<GitRef>); "mapping": ((GitMapping | (null))); });

export type Operation = ({ "operationId": Id; "jobId": Id; "repositoryId": ((Id | (null))); "worktreeId": ((Id | (null))); "action": "git.commit" | "git.fetch" | "git.push" | "git.merge" | "git.rebase" | "git.clone" | "git.init" | "git.attach" | "archive.verify" | "job.delete"; "state": "queued" | "running" | "cancelling" | "completed" | "failed" | "cancelled" | "interrupted" | "recovery-required"; "version": Version; "createdAt": Instant; "endedAt": ((Instant | (null))); "resultObjectId": ((ObjectId | (null))); "recoveryRequired": (boolean); "message": (((string) | (null))); });

export type ErrorDetail = ({ "pointer": (string); "code": Id; "message": (string); });

export type ErrorData = ({ "code": Id; "message": (string); "retryable": (boolean); "details": (Array<ErrorDetail>); "retryAfterMs": ((Uint64 | (null))); });

export type WorkflowStart = ({ "workflow": Workflow; "inputRevisionId": ((Id | (null))); "harnessCapabilityId": ((Id | (null))); "limits": ExecutionLimits; });

export type Recover = ({ "mode": "retry" | "resume"; "expectedInputRevisionId": ((Id | (null))); });

export type GitGuards = ({ "repositoryVersion": Version; "worktreeVersion": Version; "expectedHeadObjectId": ((ObjectId | (null))); "expectedRefId": ((Id | (null))); "expectedRefObjectId": ((ObjectId | (null))); });

export type GitCommit = ({ "action": "git.commit"; "worktreeId": Id; "guards": GitGuards; "selectedFileIds": (Array<Id>); "message": (string); });

export type GitPush = ({ "action": "git.push"; "worktreeId": Id; "guards": GitGuards; "remoteId": Id; "remoteRefId": Id; "localObjectId": ObjectId; "expectedRemoteObjectId": ((ObjectId | (null))); });

export type SessionStart = ({ "token": (string); });

export type Runtime = ({ "javaVersion": (string); "osName": "linux" | "macos" | "windows" | "unknown"; "architecture": "x86_64" | "aarch64" | "unknown"; "gitVersion": (((string) | (null))); });

export type UploadProgress = ({ "uploadId": (string); "receivedBytes": Uint64; "totalBytes": ((Uint64 | (null))); "state": "receiving" | "validating" | "published" | "unconfirmed"; "jobId": ((Id | (null))); });

export type Runs = ({ "items": (Array<Run>); "page": Page; "jobId": Id; });

export type ProgressObservation = ({ "authority": "observations"; "writerId": Id; "workflow": (string); "observationKind": (string); "fields": ({ "taskId"?: (string); "workflowRunId"?: (string); "revisionId"?: (string); "phase"?: (string); "status"?: (string); "stopReason"?: (string); "failureKind"?: (string); "role"?: (string); "decision"?: (string); "path"?: (string); "change"?: (string); "wallClock"?: (string); "reportedCostAmount"?: (string); "reportedCostCurrency"?: (string); "text"?: (string); "taskIdSha256"?: (string); "workflowRunIdSha256"?: (string); "revisionIdSha256"?: (string); "requestSha256"?: (string); "sessionIdSha256"?: (string); "toolCallIdSha256"?: (string); "permissionIdSha256"?: (string); "messageIdSha256"?: (string); "acceptedRevisionSha256"?: (string); "contentSha256"?: (string); "afterSha256"?: (string); "turnId"?: Id; "inputTokens"?: Uint64; "outputTokens"?: Uint64; "cachedInputTokens"?: Uint64; "toolCalls"?: Uint64; "contextUsedTokens"?: Uint64; "contextWindowTokens"?: Uint64; "chunkCharacters"?: Uint64; "entryCount"?: Uint64; "entriesTruncated"?: (boolean); "completed"?: (boolean); "validationPending"?: (boolean); "sourceSequenceGap"?: (boolean); "textOmitted"?: (boolean); "messageTrackingExhausted"?: (boolean); "entries"?: (Array<({ "idSha256": (string); "status": (string); "text": (string); })>); }); "omittedFieldCount": Uint64; });

export type ContractDocument = ((({ "apiVersion": 1; "kind": "session"; "requestId": RequestId; "data": Session; }) | ({ "apiVersion": 1; "kind": "bootstrap"; "requestId": RequestId; "data": Bootstrap; }) | ({ "apiVersion": 1; "kind": "job"; "requestId": RequestId; "data": Job; }) | ({ "apiVersion": 1; "kind": "jobs"; "requestId": RequestId; "data": Jobs; }) | ({ "apiVersion": 1; "kind": "run"; "requestId": RequestId; "data": Run; }) | ({ "apiVersion": 1; "kind": "artifact"; "requestId": RequestId; "data": Artifact; }) | ({ "apiVersion": 1; "kind": "revision"; "requestId": RequestId; "data": Revision; }) | ({ "apiVersion": 1; "kind": "report"; "requestId": RequestId; "data": Report; }) | ({ "apiVersion": 1; "kind": "snapshot"; "requestId": RequestId; "data": Snapshot; }) | ({ "apiVersion": 1; "kind": "events"; "requestId": RequestId; "data": Events; }) | ({ "apiVersion": 1; "kind": "gitWorkspace"; "requestId": RequestId; "data": GitWorkspace; }) | ({ "apiVersion": 1; "kind": "operation"; "requestId": RequestId; "data": Operation; }) | ({ "apiVersion": 1; "kind": "error"; "requestId": RequestId; "error": ErrorData; }) | ({ "apiVersion": 1; "kind": "workflowStartRequest"; "data": WorkflowStart; }) | ({ "apiVersion": 1; "kind": "recoverRequest"; "data": Recover; }) | ({ "apiVersion": 1; "kind": "gitCommitRequest"; "data": GitCommit; }) | ({ "apiVersion": 1; "kind": "gitPushRequest"; "data": GitPush; }) | ({ "apiVersion": 1; "kind": "sessionStartRequest"; "data": SessionStart; }) | WebEvent | ({ "apiVersion": 1; "kind": "uploadProgress"; "requestId": RequestId; "data": UploadProgress; }) | ({ "apiVersion": 1; "kind": "runs"; "requestId": RequestId; "data": Runs; })));
export type ResponseKind = "session" | "bootstrap" | "job" | "jobs" | "run" | "artifact" | "revision" | "report" | "snapshot" | "events" | "gitWorkspace" | "operation" | "error" | "uploadProgress" | "runs";
export type RequestKind = "workflowStartRequest" | "recoverRequest" | "gitCommitRequest" | "gitPushRequest" | "sessionStartRequest";
export type ResponseOf<K extends ResponseKind> = Extract<ContractDocument, { kind: K }>;
export type RequestData<K extends RequestKind> = Extract<ContractDocument, { kind: K }>['data'];
