// Generated by scripts/generate-web-api.mjs; do not edit.
// Source SHA-256: 5637651850fe122452f1827c1e900ec40d8e6d82996601774033734f22bfc850
import type { Schema } from './schema-types';

export const contractSchema: Schema = {
  "definitions": {
    "id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9_-]{0,127}$"
    },
    "sha256": {
      "type": "string",
      "pattern": "^[0-9a-f]{64}$"
    },
    "uint64": {
      "type": "string",
      "pattern": "^(0|[1-9][0-9]{0,18}|1[0-7][0-9]{18}|18[0-3][0-9]{17}|184[0-3][0-9]{16}|1844[0-5][0-9]{15}|18446[0-6][0-9]{14}|184467[0-3][0-9]{13}|1844674[0-3][0-9]{12}|184467440[0-6][0-9]{10}|1844674407[0-2][0-9]{9}|18446744073[0-6][0-9]{8}|1844674407370[0-8][0-9]{6}|18446744073709[0-4][0-9]{5}|184467440737095[0-4][0-9]{4}|18446744073709550[0-9]{3}|18446744073709551[0-5][0-9]{2}|1844674407370955160[0-9]{1}|1844674407370955161[0-4]|18446744073709551615)$",
      "description": "Canonical unsigned decimal string in [0, 18446744073709551615]."
    },
    "address": {
      "type": "string",
      "pattern": "^0x(0|[1-9a-f][0-9a-f]{0,15})$"
    },
    "instant": {
      "type": "string",
      "format": "date-time",
      "maxLength": 40
    },
    "objectId": {
      "type": "string",
      "pattern": "^[0-9a-f]{1,128}$",
      "description": "Full opaque Git object ID; length must match repository objectFormat, never a display abbreviation."
    },
    "version": {
      "$ref": "#/definitions/id"
    },
    "cursor": {
      "$ref": "#/definitions/id"
    },
    "binding": {
      "type": "object",
      "properties": {
        "jobId": {
          "$ref": "#/definitions/id"
        },
        "runId": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        },
        "revisionId": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "jobId",
        "runId",
        "revisionId"
      ],
      "additionalProperties": false
    },
    "acceptance": {
      "type": "string",
      "enum": [
        "not-evaluated",
        "accepted",
        "rejected",
        "unknown"
      ]
    },
    "runState": {
      "type": "string",
      "enum": [
        "queued",
        "running",
        "cancelling",
        "completed",
        "failed",
        "cancelled",
        "interrupted"
      ]
    },
    "workflow": {
      "type": "string",
      "enum": [
        "explore",
        "reconstruct",
        "build",
        "validate",
        "repair"
      ]
    },
    "requestId": {
      "$ref": "#/definitions/id"
    },
    "limits": {
      "type": "object",
      "properties": {
        "requestDeadlineMs": {
          "$ref": "#/definitions/uint64"
        },
        "uploadDeadlineMs": {
          "$ref": "#/definitions/uint64"
        },
        "downloadIdleMs": {
          "$ref": "#/definitions/uint64"
        },
        "maxJsonBytes": {
          "$ref": "#/definitions/uint64"
        },
        "maxUploadBytes": {
          "$ref": "#/definitions/uint64"
        },
        "maxSourceChunkBytes": {
          "$ref": "#/definitions/uint64"
        },
        "maxLogChunkBytes": {
          "$ref": "#/definitions/uint64"
        },
        "maxEventCount": {
          "$ref": "#/definitions/uint64"
        },
        "maxEventBytes": {
          "$ref": "#/definitions/uint64"
        },
        "terminalEventRetentionMs": {
          "$ref": "#/definitions/uint64"
        },
        "defaultPageLimit": {
          "type": "integer",
          "minimum": 1,
          "maximum": 200
        },
        "maxPageLimit": {
          "type": "integer",
          "minimum": 1,
          "maximum": 200
        }
      },
      "required": [
        "requestDeadlineMs",
        "uploadDeadlineMs",
        "downloadIdleMs",
        "maxJsonBytes",
        "maxUploadBytes",
        "maxSourceChunkBytes",
        "maxLogChunkBytes",
        "maxEventCount",
        "maxEventBytes",
        "terminalEventRetentionMs",
        "defaultPageLimit",
        "maxPageLimit"
      ],
      "additionalProperties": false
    },
    "capability": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/definitions/id"
        },
        "state": {
          "type": "string",
          "enum": [
            "supported",
            "unavailable",
            "unsupported",
            "unknown"
          ]
        },
        "reasonCode": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        },
        "message": {
          "anyOf": [
            {
              "type": "string",
              "maxLength": 500
            },
            {
              "type": "null"
            }
          ]
        },
        "workflows": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/workflow"
          },
          "maxItems": 5
        },
        "agentContractVersion": {
          "anyOf": [
            {
              "type": "integer",
              "minimum": 1,
              "maximum": 65535
            },
            {
              "type": "null"
            }
          ]
        },
        "limits": {
          "anyOf": [
            {
              "$ref": "#/definitions/executionLimits"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "id",
        "state",
        "reasonCode",
        "message",
        "workflows",
        "agentContractVersion",
        "limits"
      ],
      "additionalProperties": false
    },
    "bootstrap": {
      "type": "object",
      "properties": {
        "apiVersions": {
          "type": "array",
          "items": {
            "type": "integer",
            "minimum": 1,
            "maximum": 65535
          },
          "maxItems": 8
        },
        "applicationBuildId": {
          "$ref": "#/definitions/id"
        },
        "uiBuildId": {
          "$ref": "#/definitions/id"
        },
        "basePath": {
          "type": "string",
          "pattern": "^/([^?#]+/)?$",
          "maxLength": 256
        },
        "readiness": {
          "type": "string",
          "enum": [
            "ready",
            "degraded",
            "draining",
            "unavailable"
          ]
        },
        "sessionExpiresAt": {
          "$ref": "#/definitions/instant"
        },
        "capabilities": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/capability"
          },
          "maxItems": 128
        },
        "limits": {
          "$ref": "#/definitions/limits"
        },
        "runtime": {
          "$ref": "#/definitions/runtime"
        },
        "csrfToken": {
          "type": "string",
          "minLength": 32,
          "maxLength": 256,
          "pattern": "^[A-Za-z0-9_-]+$"
        }
      },
      "required": [
        "apiVersions",
        "applicationBuildId",
        "uiBuildId",
        "basePath",
        "readiness",
        "sessionExpiresAt",
        "capabilities",
        "limits",
        "runtime",
        "csrfToken"
      ],
      "additionalProperties": false
    },
    "session": {
      "type": "object",
      "properties": {
        "csrfToken": {
          "type": "string",
          "minLength": 32,
          "maxLength": 256,
          "pattern": "^[A-Za-z0-9_-]+$"
        },
        "expiresAt": {
          "$ref": "#/definitions/instant"
        }
      },
      "required": [
        "csrfToken",
        "expiresAt"
      ],
      "additionalProperties": false
    },
    "binary": {
      "type": "object",
      "properties": {
        "format": {
          "type": "string",
          "maxLength": 16
        },
        "endianness": {
          "type": "string",
          "enum": [
            "little",
            "big"
          ]
        },
        "objectType": {
          "type": "string",
          "maxLength": 64
        },
        "machine": {
          "type": "string",
          "maxLength": 64
        },
        "osAbi": {
          "type": "string",
          "maxLength": 64
        },
        "entryPoint": {
          "$ref": "#/definitions/address"
        }
      },
      "required": [
        "format",
        "endianness",
        "objectType",
        "machine",
        "osAbi",
        "entryPoint"
      ],
      "additionalProperties": false
    },
    "job": {
      "type": "object",
      "properties": {
        "jobId": {
          "$ref": "#/definitions/id"
        },
        "displayFilename": {
          "type": "string",
          "maxLength": 255
        },
        "status": {
          "type": "string",
          "enum": [
            "uploaded",
            "queued",
            "running",
            "completed",
            "failed",
            "cancelled",
            "interrupted",
            "unknown"
          ]
        },
        "createdAt": {
          "$ref": "#/definitions/instant"
        },
        "updatedAt": {
          "$ref": "#/definitions/instant"
        },
        "sizeBytes": {
          "$ref": "#/definitions/uint64"
        },
        "binary": {
          "$ref": "#/definitions/binary"
        },
        "version": {
          "$ref": "#/definitions/version"
        },
        "latestRunId": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        },
        "acceptedRevisionId": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "jobId",
        "displayFilename",
        "status",
        "createdAt",
        "updatedAt",
        "sizeBytes",
        "binary",
        "version",
        "latestRunId",
        "acceptedRevisionId"
      ],
      "additionalProperties": false
    },
    "page": {
      "type": "object",
      "properties": {
        "nextCursor": {
          "anyOf": [
            {
              "$ref": "#/definitions/cursor"
            },
            {
              "type": "null"
            }
          ]
        },
        "snapshotVersion": {
          "$ref": "#/definitions/version"
        },
        "limit": {
          "type": "integer",
          "minimum": 1,
          "maximum": 200
        }
      },
      "required": [
        "nextCursor",
        "snapshotVersion",
        "limit"
      ],
      "additionalProperties": false
    },
    "jobs": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/job"
          },
          "maxItems": 200
        },
        "page": {
          "$ref": "#/definitions/page"
        }
      },
      "required": [
        "items",
        "page"
      ],
      "additionalProperties": false
    },
    "executionLimits": {
      "type": "object",
      "properties": {
        "wallClockMs": {
          "$ref": "#/definitions/uint64"
        },
        "idleMs": {
          "$ref": "#/definitions/uint64"
        },
        "maxOutputBytes": {
          "$ref": "#/definitions/uint64"
        },
        "maxToolCalls": {
          "$ref": "#/definitions/uint64"
        }
      },
      "required": [
        "wallClockMs",
        "idleMs",
        "maxOutputBytes",
        "maxToolCalls"
      ],
      "additionalProperties": false
    },
    "usage": {
      "type": "object",
      "properties": {
        "inputTokens": {
          "anyOf": [
            {
              "$ref": "#/definitions/uint64"
            },
            {
              "type": "null"
            }
          ]
        },
        "outputTokens": {
          "anyOf": [
            {
              "$ref": "#/definitions/uint64"
            },
            {
              "type": "null"
            }
          ]
        },
        "cachedInputTokens": {
          "anyOf": [
            {
              "$ref": "#/definitions/uint64"
            },
            {
              "type": "null"
            }
          ]
        },
        "toolCalls": {
          "anyOf": [
            {
              "$ref": "#/definitions/uint64"
            },
            {
              "type": "null"
            }
          ]
        },
        "wallClockMs": {
          "anyOf": [
            {
              "$ref": "#/definitions/uint64"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "inputTokens",
        "outputTokens",
        "cachedInputTokens",
        "toolCalls",
        "wallClockMs"
      ],
      "additionalProperties": false
    },
    "run": {
      "type": "object",
      "properties": {
        "runId": {
          "$ref": "#/definitions/id"
        },
        "jobId": {
          "$ref": "#/definitions/id"
        },
        "workflow": {
          "$ref": "#/definitions/workflow"
        },
        "state": {
          "$ref": "#/definitions/runState"
        },
        "version": {
          "$ref": "#/definitions/version"
        },
        "createdAt": {
          "$ref": "#/definitions/instant"
        },
        "startedAt": {
          "anyOf": [
            {
              "$ref": "#/definitions/instant"
            },
            {
              "type": "null"
            }
          ]
        },
        "endedAt": {
          "anyOf": [
            {
              "$ref": "#/definitions/instant"
            },
            {
              "type": "null"
            }
          ]
        },
        "previousRunId": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        },
        "inputRevisionId": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        },
        "resultRevisionId": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        },
        "acceptance": {
          "$ref": "#/definitions/acceptance"
        },
        "harnessCapabilityId": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        },
        "terminalReason": {
          "anyOf": [
            {
              "type": "string",
              "enum": [
                "COMPLETED",
                "NO_CHANGES",
                "REFUSED",
                "CANCELLED",
                "LIMIT_EXHAUSTED",
                "FAILED",
                "PROCESS_INTERRUPTED"
              ]
            },
            {
              "type": "null"
            }
          ]
        },
        "usage": {
          "anyOf": [
            {
              "$ref": "#/definitions/usage"
            },
            {
              "type": "null"
            }
          ]
        },
        "limits": {
          "$ref": "#/definitions/executionLimits"
        }
      },
      "required": [
        "runId",
        "jobId",
        "workflow",
        "state",
        "version",
        "createdAt",
        "startedAt",
        "endedAt",
        "previousRunId",
        "inputRevisionId",
        "resultRevisionId",
        "acceptance",
        "harnessCapabilityId",
        "terminalReason",
        "usage",
        "limits"
      ],
      "additionalProperties": false,
      "allOf": [
        {
          "if": {
            "properties": {
              "state": {
                "enum": [
                  "completed",
                  "failed",
                  "cancelled",
                  "interrupted"
                ]
              }
            }
          },
          "then": {
            "properties": {
              "endedAt": {
                "$ref": "#/definitions/instant"
              },
              "terminalReason": {
                "type": "string"
              }
            }
          },
          "else": {
            "properties": {
              "endedAt": {
                "type": "null"
              },
              "terminalReason": {
                "type": "null"
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "state": {
                "const": "queued"
              }
            }
          },
          "then": {
            "properties": {
              "startedAt": {
                "type": "null"
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "acceptance": {
                "const": "accepted"
              }
            }
          },
          "then": {
            "properties": {
              "state": {
                "const": "completed"
              },
              "resultRevisionId": {
                "$ref": "#/definitions/id"
              }
            }
          }
        }
      ]
    },
    "artifact": {
      "type": "object",
      "properties": {
        "artifactId": {
          "$ref": "#/definitions/id"
        },
        "binding": {
          "$ref": "#/definitions/binding"
        },
        "displayName": {
          "type": "string",
          "maxLength": 255
        },
        "mediaType": {
          "type": "string",
          "maxLength": 128
        },
        "sizeBytes": {
          "$ref": "#/definitions/uint64"
        },
        "sha256": {
          "$ref": "#/definitions/sha256"
        },
        "contentHref": {
          "type": "string",
          "pattern": "^/[^?#]*api/v1/jobs/[A-Za-z0-9_-]+/artifacts/[A-Za-z0-9_-]+/content$",
          "maxLength": 1024
        },
        "role": {
          "type": "string",
          "enum": [
            "raw-evidence",
            "sanitized-derivative",
            "source",
            "archive"
          ]
        },
        "derivedFromArtifactId": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "artifactId",
        "binding",
        "displayName",
        "mediaType",
        "sizeBytes",
        "sha256",
        "contentHref",
        "role",
        "derivedFromArtifactId"
      ],
      "additionalProperties": false,
      "allOf": [
        {
          "if": {
            "properties": {
              "role": {
                "const": "sanitized-derivative"
              }
            }
          },
          "then": {
            "properties": {
              "derivedFromArtifactId": {
                "$ref": "#/definitions/id"
              }
            }
          }
        }
      ]
    },
    "revision": {
      "type": "object",
      "properties": {
        "revisionId": {
          "$ref": "#/definitions/id"
        },
        "jobId": {
          "$ref": "#/definitions/id"
        },
        "runId": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        },
        "sourceSha256": {
          "$ref": "#/definitions/sha256"
        },
        "parentRevisionId": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        },
        "graphNodeId": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        },
        "graphStatus": {
          "anyOf": [
            {
              "type": "string",
              "enum": [
                "ROOT",
                "ACCEPTED",
                "REJECTED"
              ]
            },
            {
              "type": "null"
            }
          ]
        },
        "acceptance": {
          "$ref": "#/definitions/acceptance"
        },
        "acceptanceArtifactId": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        },
        "publicationMode": {
          "type": "string",
          "enum": [
            "release",
            "test-only",
            "unknown"
          ]
        }
      },
      "required": [
        "revisionId",
        "jobId",
        "runId",
        "sourceSha256",
        "parentRevisionId",
        "graphNodeId",
        "graphStatus",
        "acceptance",
        "acceptanceArtifactId",
        "publicationMode"
      ],
      "additionalProperties": false,
      "allOf": [
        {
          "if": {
            "properties": {
              "acceptance": {
                "const": "accepted"
              }
            }
          },
          "then": {
            "properties": {
              "graphStatus": {
                "const": "ACCEPTED"
              },
              "graphNodeId": {
                "$ref": "#/definitions/id"
              },
              "acceptanceArtifactId": {
                "$ref": "#/definitions/id"
              },
              "publicationMode": {
                "const": "release"
              }
            }
          }
        }
      ]
    },
    "explorationSummary": {
      "type": "object",
      "properties": {
        "candidateCount": {
          "$ref": "#/definitions/uint64"
        },
        "expandedOutputSignatures": {
          "$ref": "#/definitions/uint64"
        },
        "confidence": {
          "type": "object",
          "properties": {
            "score": {
              "type": "number",
              "minimum": 0,
              "maximum": 1
            },
            "inputCount": {
              "$ref": "#/definitions/uint64"
            },
            "sourceCount": {
              "$ref": "#/definitions/uint64"
            },
            "outputSignatureCount": {
              "$ref": "#/definitions/uint64"
            },
            "newOutputSignatureCount": {
              "$ref": "#/definitions/uint64"
            },
            "sandboxed": {
              "type": "boolean"
            },
            "networkIsolated": {
              "type": "boolean"
            }
          },
          "required": [
            "score",
            "inputCount",
            "sourceCount",
            "outputSignatureCount",
            "newOutputSignatureCount",
            "sandboxed",
            "networkIsolated"
          ],
          "additionalProperties": false
        }
      },
      "required": [
        "candidateCount",
        "expandedOutputSignatures",
        "confidence"
      ],
      "additionalProperties": false
    },
    "validationSummary": {
      "type": "object",
      "properties": {
        "result": {
          "type": "string",
          "enum": [
            "passed",
            "failed",
            "unknown"
          ]
        },
        "casesCompared": {
          "$ref": "#/definitions/uint64"
        },
        "sourceSha256": {
          "$ref": "#/definitions/sha256"
        }
      },
      "required": [
        "result",
        "casesCompared",
        "sourceSha256"
      ],
      "additionalProperties": false
    },
    "report": {
      "type": "object",
      "properties": {
        "reportId": {
          "$ref": "#/definitions/id"
        },
        "binding": {
          "$ref": "#/definitions/binding"
        },
        "reportType": {
          "type": "string",
          "enum": [
            "exploration",
            "revision-validation",
            "unknown"
          ]
        },
        "adapterVersion": {
          "type": "integer",
          "minimum": 1,
          "maximum": 65535
        },
        "producerSchemaVersion": {
          "anyOf": [
            {
              "type": "integer",
              "minimum": 1,
              "maximum": 65535
            },
            {
              "type": "null"
            }
          ]
        },
        "state": {
          "type": "string",
          "enum": [
            "available",
            "partial",
            "missing",
            "unsupported",
            "unknown",
            "invalid",
            "incompatible"
          ]
        },
        "authority": {
          "type": "string",
          "enum": [
            "observations",
            "canonical-validation",
            "canonical-revision-graph",
            "derived-presentation",
            "unknown"
          ]
        },
        "sourceArtifact": {
          "anyOf": [
            {
              "$ref": "#/definitions/artifact"
            },
            {
              "type": "null"
            }
          ]
        },
        "acceptance": {
          "$ref": "#/definitions/acceptance"
        },
        "acceptanceArtifactId": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        },
        "limitations": {
          "type": "array",
          "items": {
            "type": "string",
            "maxLength": 500
          },
          "maxItems": 32
        },
        "summary": {
          "anyOf": [
            {
              "oneOf": [
                {
                  "$ref": "#/definitions/explorationSummary"
                },
                {
                  "$ref": "#/definitions/validationSummary"
                }
              ]
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "reportId",
        "binding",
        "reportType",
        "adapterVersion",
        "producerSchemaVersion",
        "state",
        "authority",
        "sourceArtifact",
        "acceptance",
        "acceptanceArtifactId",
        "limitations",
        "summary"
      ],
      "additionalProperties": false,
      "allOf": [
        {
          "if": {
            "properties": {
              "state": {
                "enum": [
                  "missing",
                  "unsupported",
                  "unknown",
                  "invalid",
                  "incompatible"
                ]
              }
            }
          },
          "then": {
            "properties": {
              "summary": {
                "type": "null"
              },
              "acceptance": {
                "enum": [
                  "not-evaluated",
                  "unknown"
                ]
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "acceptance": {
                "const": "accepted"
              }
            }
          },
          "then": {
            "properties": {
              "state": {
                "const": "available"
              },
              "authority": {
                "enum": [
                  "canonical-validation",
                  "canonical-revision-graph"
                ]
              },
              "acceptanceArtifactId": {
                "$ref": "#/definitions/id"
              },
              "binding": {
                "properties": {
                  "revisionId": {
                    "$ref": "#/definitions/id"
                  }
                }
              },
              "sourceArtifact": {
                "$ref": "#/definitions/artifact"
              }
            }
          }
        }
      ]
    },
    "eventBase": {
      "type": "object",
      "properties": {
        "apiVersion": {
          "const": 1
        },
        "kind": {
          "const": "event"
        },
        "type": {
          "type": "string",
          "enum": [
            "agent.message",
            "run.state",
            "evidence.available",
            "retention.gap",
            "workflow.observation"
          ]
        },
        "jobId": {
          "$ref": "#/definitions/id"
        },
        "runId": {
          "$ref": "#/definitions/id"
        },
        "cursor": {
          "anyOf": [
            {
              "$ref": "#/definitions/cursor"
            },
            {
              "type": "null"
            }
          ]
        },
        "sequence": {
          "anyOf": [
            {
              "$ref": "#/definitions/uint64"
            },
            {
              "type": "null"
            }
          ]
        },
        "occurredAt": {
          "$ref": "#/definitions/instant"
        },
        "originRequestId": {
          "anyOf": [
            {
              "$ref": "#/definitions/requestId"
            },
            {
              "type": "null"
            }
          ]
        },
        "agentInvocationId": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        },
        "agentSequence": {
          "anyOf": [
            {
              "$ref": "#/definitions/uint64"
            },
            {
              "type": "null"
            }
          ]
        },
        "payload": {
          "type": "object"
        }
      },
      "required": [
        "apiVersion",
        "kind",
        "type",
        "jobId",
        "runId",
        "cursor",
        "sequence",
        "occurredAt",
        "originRequestId",
        "agentInvocationId",
        "agentSequence",
        "payload"
      ],
      "additionalProperties": false
    },
    "event": {
      "allOf": [
        {
          "$ref": "#/definitions/eventBase"
        }
      ],
      "oneOf": [
        {
          "properties": {
            "type": {
              "const": "agent.message"
            },
            "payload": {
              "type": "object",
              "properties": {
                "messageId": {
                  "$ref": "#/definitions/id"
                },
                "role": {
                  "type": "string",
                  "enum": [
                    "ASSISTANT",
                    "USER",
                    "SYSTEM"
                  ]
                },
                "textDelta": {
                  "type": "string",
                  "maxLength": 65536
                },
                "completed": {
                  "type": "boolean"
                }
              },
              "required": [
                "messageId",
                "role",
                "textDelta",
                "completed"
              ],
              "additionalProperties": false
            },
            "agentInvocationId": {
              "$ref": "#/definitions/id"
            },
            "agentSequence": {
              "$ref": "#/definitions/uint64"
            },
            "cursor": {
              "$ref": "#/definitions/cursor"
            },
            "sequence": {
              "$ref": "#/definitions/uint64"
            }
          }
        },
        {
          "properties": {
            "type": {
              "const": "run.state"
            },
            "payload": {
              "type": "object",
              "properties": {
                "state": {
                  "$ref": "#/definitions/runState"
                },
                "version": {
                  "$ref": "#/definitions/version"
                },
                "acceptance": {
                  "$ref": "#/definitions/acceptance"
                }
              },
              "required": [
                "state",
                "version",
                "acceptance"
              ],
              "additionalProperties": false
            },
            "agentInvocationId": {
              "type": "null"
            },
            "agentSequence": {
              "type": "null"
            },
            "cursor": {
              "$ref": "#/definitions/cursor"
            },
            "sequence": {
              "$ref": "#/definitions/uint64"
            }
          }
        },
        {
          "properties": {
            "type": {
              "const": "evidence.available"
            },
            "payload": {
              "type": "object",
              "properties": {
                "artifactId": {
                  "$ref": "#/definitions/id"
                },
                "revisionId": {
                  "anyOf": [
                    {
                      "$ref": "#/definitions/id"
                    },
                    {
                      "type": "null"
                    }
                  ]
                }
              },
              "required": [
                "artifactId",
                "revisionId"
              ],
              "additionalProperties": false
            },
            "agentInvocationId": {
              "type": "null"
            },
            "agentSequence": {
              "type": "null"
            },
            "cursor": {
              "$ref": "#/definitions/cursor"
            },
            "sequence": {
              "$ref": "#/definitions/uint64"
            }
          }
        },
        {
          "properties": {
            "type": {
              "const": "retention.gap"
            },
            "payload": {
              "type": "object",
              "properties": {
                "requestedCursor": {
                  "$ref": "#/definitions/cursor"
                },
                "oldestCursor": {
                  "anyOf": [
                    {
                      "$ref": "#/definitions/cursor"
                    },
                    {
                      "type": "null"
                    }
                  ]
                },
                "latestCursor": {
                  "anyOf": [
                    {
                      "$ref": "#/definitions/cursor"
                    },
                    {
                      "type": "null"
                    }
                  ]
                },
                "snapshotHref": {
                  "type": "string",
                  "pattern": "^/[^?#]*api/v1/jobs/[A-Za-z0-9_-]+/runs/[A-Za-z0-9_-]+/snapshot$",
                  "maxLength": 1024
                }
              },
              "required": [
                "requestedCursor",
                "oldestCursor",
                "latestCursor",
                "snapshotHref"
              ],
              "additionalProperties": false
            },
            "agentInvocationId": {
              "type": "null"
            },
            "agentSequence": {
              "type": "null"
            },
            "cursor": {
              "type": "null"
            },
            "sequence": {
              "type": "null"
            }
          }
        },
        {
          "properties": {
            "type": {
              "const": "workflow.observation"
            },
            "payload": {
              "$ref": "#/definitions/progressObservation"
            },
            "cursor": {
              "$ref": "#/definitions/cursor"
            },
            "sequence": {
              "$ref": "#/definitions/uint64"
            },
            "agentInvocationId": {
              "type": "null"
            }
          }
        }
      ]
    },
    "snapshot": {
      "type": "object",
      "properties": {
        "run": {
          "$ref": "#/definitions/run"
        },
        "throughCursor": {
          "anyOf": [
            {
              "$ref": "#/definitions/cursor"
            },
            {
              "type": "null"
            }
          ]
        },
        "throughSequence": {
          "anyOf": [
            {
              "$ref": "#/definitions/uint64"
            },
            {
              "type": "null"
            }
          ]
        },
        "oldestCursor": {
          "anyOf": [
            {
              "$ref": "#/definitions/cursor"
            },
            {
              "type": "null"
            }
          ]
        },
        "progress": {
          "type": "object",
          "properties": {
            "authority": {
              "const": "observations"
            },
            "nextSequence": {
              "$ref": "#/definitions/uint64"
            },
            "queueDropped": {
              "$ref": "#/definitions/uint64"
            },
            "historyDropped": {
              "$ref": "#/definitions/uint64"
            },
            "retainedEventCount": {
              "$ref": "#/definitions/uint64"
            }
          },
          "required": [
            "authority",
            "nextSequence",
            "queueDropped",
            "historyDropped",
            "retainedEventCount"
          ],
          "additionalProperties": false
        }
      },
      "required": [
        "run",
        "throughCursor",
        "throughSequence",
        "oldestCursor"
      ],
      "additionalProperties": false
    },
    "events": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/event"
          },
          "maxItems": 200
        },
        "nextCursor": {
          "anyOf": [
            {
              "$ref": "#/definitions/cursor"
            },
            {
              "type": "null"
            }
          ]
        },
        "hasMore": {
          "type": "boolean"
        }
      },
      "required": [
        "items",
        "nextCursor",
        "hasMore"
      ],
      "additionalProperties": false
    },
    "gitRef": {
      "type": "object",
      "properties": {
        "refId": {
          "$ref": "#/definitions/id"
        },
        "displayName": {
          "type": "string",
          "maxLength": 1024
        },
        "objectId": {
          "anyOf": [
            {
              "$ref": "#/definitions/objectId"
            },
            {
              "type": "null"
            }
          ]
        },
        "version": {
          "$ref": "#/definitions/version"
        }
      },
      "required": [
        "refId",
        "displayName",
        "objectId",
        "version"
      ],
      "additionalProperties": false
    },
    "gitMapping": {
      "type": "object",
      "properties": {
        "repositoryId": {
          "$ref": "#/definitions/id"
        },
        "objectId": {
          "$ref": "#/definitions/objectId"
        },
        "revisionId": {
          "$ref": "#/definitions/id"
        },
        "sourceSha256": {
          "$ref": "#/definitions/sha256"
        },
        "archiveArtifactId": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        },
        "acceptance": {
          "$ref": "#/definitions/acceptance"
        },
        "acceptanceArtifactId": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "repositoryId",
        "objectId",
        "revisionId",
        "sourceSha256",
        "archiveArtifactId",
        "acceptance",
        "acceptanceArtifactId"
      ],
      "additionalProperties": false
    },
    "gitWorkspace": {
      "type": "object",
      "properties": {
        "repositoryId": {
          "$ref": "#/definitions/id"
        },
        "worktreeId": {
          "$ref": "#/definitions/id"
        },
        "repositoryVersion": {
          "$ref": "#/definitions/version"
        },
        "worktreeVersion": {
          "$ref": "#/definitions/version"
        },
        "objectFormat": {
          "type": "string",
          "enum": [
            "sha1",
            "sha256",
            "unknown"
          ]
        },
        "headObjectId": {
          "anyOf": [
            {
              "$ref": "#/definitions/objectId"
            },
            {
              "type": "null"
            }
          ]
        },
        "headRefId": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        },
        "candidateRevisionId": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        },
        "dirty": {
          "type": "boolean"
        },
        "refs": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/gitRef"
          },
          "maxItems": 200
        },
        "mapping": {
          "anyOf": [
            {
              "$ref": "#/definitions/gitMapping"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "repositoryId",
        "worktreeId",
        "repositoryVersion",
        "worktreeVersion",
        "objectFormat",
        "headObjectId",
        "headRefId",
        "candidateRevisionId",
        "dirty",
        "refs",
        "mapping"
      ],
      "additionalProperties": false
    },
    "operation": {
      "type": "object",
      "properties": {
        "operationId": {
          "$ref": "#/definitions/id"
        },
        "jobId": {
          "$ref": "#/definitions/id"
        },
        "repositoryId": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        },
        "worktreeId": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        },
        "action": {
          "type": "string",
          "enum": [
            "git.commit",
            "git.fetch",
            "git.push",
            "git.merge",
            "git.rebase",
            "git.clone",
            "git.init",
            "git.attach",
            "archive.verify",
            "job.delete"
          ]
        },
        "state": {
          "type": "string",
          "enum": [
            "queued",
            "running",
            "cancelling",
            "completed",
            "failed",
            "cancelled",
            "interrupted",
            "recovery-required"
          ]
        },
        "version": {
          "$ref": "#/definitions/version"
        },
        "createdAt": {
          "$ref": "#/definitions/instant"
        },
        "endedAt": {
          "anyOf": [
            {
              "$ref": "#/definitions/instant"
            },
            {
              "type": "null"
            }
          ]
        },
        "resultObjectId": {
          "anyOf": [
            {
              "$ref": "#/definitions/objectId"
            },
            {
              "type": "null"
            }
          ]
        },
        "recoveryRequired": {
          "type": "boolean"
        },
        "message": {
          "anyOf": [
            {
              "type": "string",
              "maxLength": 500
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "operationId",
        "jobId",
        "repositoryId",
        "worktreeId",
        "action",
        "state",
        "version",
        "createdAt",
        "endedAt",
        "resultObjectId",
        "recoveryRequired",
        "message"
      ],
      "additionalProperties": false
    },
    "errorDetail": {
      "type": "object",
      "properties": {
        "pointer": {
          "type": "string",
          "pattern": "^(/|$)",
          "maxLength": 256
        },
        "code": {
          "$ref": "#/definitions/id"
        },
        "message": {
          "type": "string",
          "maxLength": 500
        }
      },
      "required": [
        "pointer",
        "code",
        "message"
      ],
      "additionalProperties": false
    },
    "error": {
      "type": "object",
      "properties": {
        "code": {
          "$ref": "#/definitions/id"
        },
        "message": {
          "type": "string",
          "maxLength": 500
        },
        "retryable": {
          "type": "boolean"
        },
        "details": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/errorDetail"
          },
          "maxItems": 32
        },
        "retryAfterMs": {
          "anyOf": [
            {
              "$ref": "#/definitions/uint64"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "code",
        "message",
        "retryable",
        "details",
        "retryAfterMs"
      ],
      "additionalProperties": false
    },
    "workflowStart": {
      "type": "object",
      "properties": {
        "workflow": {
          "$ref": "#/definitions/workflow"
        },
        "inputRevisionId": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        },
        "harnessCapabilityId": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        },
        "limits": {
          "$ref": "#/definitions/executionLimits"
        }
      },
      "required": [
        "workflow",
        "inputRevisionId",
        "harnessCapabilityId",
        "limits"
      ],
      "additionalProperties": false
    },
    "recover": {
      "type": "object",
      "properties": {
        "mode": {
          "type": "string",
          "enum": [
            "retry",
            "resume"
          ]
        },
        "expectedInputRevisionId": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "mode",
        "expectedInputRevisionId"
      ],
      "additionalProperties": false
    },
    "gitGuards": {
      "type": "object",
      "properties": {
        "repositoryVersion": {
          "$ref": "#/definitions/version"
        },
        "worktreeVersion": {
          "$ref": "#/definitions/version"
        },
        "expectedHeadObjectId": {
          "anyOf": [
            {
              "$ref": "#/definitions/objectId"
            },
            {
              "type": "null"
            }
          ]
        },
        "expectedRefId": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        },
        "expectedRefObjectId": {
          "anyOf": [
            {
              "$ref": "#/definitions/objectId"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "repositoryVersion",
        "worktreeVersion",
        "expectedHeadObjectId",
        "expectedRefId",
        "expectedRefObjectId"
      ],
      "additionalProperties": false
    },
    "gitCommit": {
      "type": "object",
      "properties": {
        "action": {
          "const": "git.commit"
        },
        "worktreeId": {
          "$ref": "#/definitions/id"
        },
        "guards": {
          "$ref": "#/definitions/gitGuards"
        },
        "selectedFileIds": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/id"
          },
          "maxItems": 200,
          "minItems": 1,
          "uniqueItems": true
        },
        "message": {
          "type": "string",
          "minLength": 1,
          "maxLength": 8192
        }
      },
      "required": [
        "action",
        "worktreeId",
        "guards",
        "selectedFileIds",
        "message"
      ],
      "additionalProperties": false
    },
    "gitPush": {
      "type": "object",
      "properties": {
        "action": {
          "const": "git.push"
        },
        "worktreeId": {
          "$ref": "#/definitions/id"
        },
        "guards": {
          "$ref": "#/definitions/gitGuards"
        },
        "remoteId": {
          "$ref": "#/definitions/id"
        },
        "remoteRefId": {
          "$ref": "#/definitions/id"
        },
        "localObjectId": {
          "$ref": "#/definitions/objectId"
        },
        "expectedRemoteObjectId": {
          "anyOf": [
            {
              "$ref": "#/definitions/objectId"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "action",
        "worktreeId",
        "guards",
        "remoteId",
        "remoteRefId",
        "localObjectId",
        "expectedRemoteObjectId"
      ],
      "additionalProperties": false
    },
    "sessionStart": {
      "type": "object",
      "properties": {
        "token": {
          "type": "string",
          "minLength": 32,
          "maxLength": 256,
          "pattern": "^[A-Za-z0-9_-]+$"
        }
      },
      "required": [
        "token"
      ],
      "additionalProperties": false
    },
    "runtime": {
      "type": "object",
      "properties": {
        "javaVersion": {
          "type": "string",
          "maxLength": 64
        },
        "osName": {
          "type": "string",
          "enum": [
            "linux",
            "macos",
            "windows",
            "unknown"
          ]
        },
        "architecture": {
          "type": "string",
          "enum": [
            "x86_64",
            "aarch64",
            "unknown"
          ]
        },
        "gitVersion": {
          "anyOf": [
            {
              "type": "string",
              "maxLength": 64
            },
            {
              "type": "null"
            }
          ]
        },
        "scheduler": {
          "$ref": "#/definitions/scheduler"
        }
      },
      "required": [
        "javaVersion",
        "osName",
        "architecture",
        "gitVersion"
      ],
      "additionalProperties": false
    },
    "uploadProgress": {
      "type": "object",
      "properties": {
        "uploadId": {
          "type": "string",
          "pattern": "^[a-f0-9]{32}$"
        },
        "receivedBytes": {
          "$ref": "#/definitions/uint64"
        },
        "totalBytes": {
          "anyOf": [
            {
              "$ref": "#/definitions/uint64"
            },
            {
              "type": "null"
            }
          ]
        },
        "state": {
          "type": "string",
          "enum": [
            "receiving",
            "validating",
            "published",
            "unconfirmed"
          ]
        },
        "jobId": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "uploadId",
        "receivedBytes",
        "totalBytes",
        "state",
        "jobId"
      ],
      "additionalProperties": false
    },
    "runs": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/run"
          },
          "maxItems": 200
        },
        "page": {
          "$ref": "#/definitions/page"
        },
        "jobId": {
          "$ref": "#/definitions/id"
        }
      },
      "required": [
        "items",
        "page",
        "jobId"
      ],
      "additionalProperties": false
    },
    "progressObservation": {
      "type": "object",
      "properties": {
        "authority": {
          "const": "observations"
        },
        "writerId": {
          "$ref": "#/definitions/id"
        },
        "workflow": {
          "type": "string",
          "pattern": "^[a-z][a-z0-9-]{0,63}$"
        },
        "observationKind": {
          "type": "string",
          "pattern": "^[a-z][a-z0-9_]{0,63}$"
        },
        "fields": {
          "type": "object",
          "properties": {
            "taskId": {
              "type": "string",
              "maxLength": 533
            },
            "workflowRunId": {
              "type": "string",
              "maxLength": 533
            },
            "revisionId": {
              "type": "string",
              "maxLength": 533
            },
            "phase": {
              "type": "string",
              "maxLength": 533
            },
            "status": {
              "type": "string",
              "maxLength": 533
            },
            "stopReason": {
              "type": "string",
              "maxLength": 533
            },
            "failureKind": {
              "type": "string",
              "maxLength": 533
            },
            "role": {
              "type": "string",
              "maxLength": 533
            },
            "decision": {
              "type": "string",
              "maxLength": 533
            },
            "path": {
              "type": "string",
              "maxLength": 533
            },
            "change": {
              "type": "string",
              "maxLength": 533
            },
            "wallClock": {
              "type": "string",
              "maxLength": 533
            },
            "reportedCostAmount": {
              "type": "string",
              "maxLength": 533
            },
            "reportedCostCurrency": {
              "type": "string",
              "maxLength": 533
            },
            "text": {
              "type": "string",
              "maxLength": 8192
            },
            "taskIdSha256": {
              "type": "string",
              "pattern": "^[a-f0-9]{64}$"
            },
            "workflowRunIdSha256": {
              "type": "string",
              "pattern": "^[a-f0-9]{64}$"
            },
            "revisionIdSha256": {
              "type": "string",
              "pattern": "^[a-f0-9]{64}$"
            },
            "requestSha256": {
              "type": "string",
              "pattern": "^[a-f0-9]{64}$"
            },
            "sessionIdSha256": {
              "type": "string",
              "pattern": "^[a-f0-9]{64}$"
            },
            "toolCallIdSha256": {
              "type": "string",
              "pattern": "^[a-f0-9]{64}$"
            },
            "permissionIdSha256": {
              "type": "string",
              "pattern": "^[a-f0-9]{64}$"
            },
            "messageIdSha256": {
              "type": "string",
              "pattern": "^[a-f0-9]{64}$"
            },
            "acceptedRevisionSha256": {
              "type": "string",
              "pattern": "^[a-f0-9]{64}$"
            },
            "contentSha256": {
              "type": "string",
              "pattern": "^[a-f0-9]{64}$"
            },
            "afterSha256": {
              "type": "string",
              "pattern": "^[a-f0-9]{64}$"
            },
            "turnId": {
              "$ref": "#/definitions/id"
            },
            "inputTokens": {
              "$ref": "#/definitions/uint64"
            },
            "outputTokens": {
              "$ref": "#/definitions/uint64"
            },
            "cachedInputTokens": {
              "$ref": "#/definitions/uint64"
            },
            "toolCalls": {
              "$ref": "#/definitions/uint64"
            },
            "contextUsedTokens": {
              "$ref": "#/definitions/uint64"
            },
            "contextWindowTokens": {
              "$ref": "#/definitions/uint64"
            },
            "chunkCharacters": {
              "$ref": "#/definitions/uint64"
            },
            "entryCount": {
              "$ref": "#/definitions/uint64"
            },
            "entriesTruncated": {
              "type": "boolean"
            },
            "completed": {
              "type": "boolean"
            },
            "validationPending": {
              "type": "boolean"
            },
            "sourceSequenceGap": {
              "type": "boolean"
            },
            "textOmitted": {
              "type": "boolean"
            },
            "messageTrackingExhausted": {
              "type": "boolean"
            },
            "entries": {
              "type": "array",
              "maxItems": 8,
              "items": {
                "type": "object",
                "properties": {
                  "idSha256": {
                    "type": "string",
                    "pattern": "^[a-f0-9]{64}$"
                  },
                  "status": {
                    "type": "string",
                    "maxLength": 64
                  },
                  "text": {
                    "type": "string",
                    "maxLength": 181
                  }
                },
                "required": [
                  "idSha256",
                  "status",
                  "text"
                ],
                "additionalProperties": false
              }
            }
          },
          "additionalProperties": false
        },
        "omittedFieldCount": {
          "$ref": "#/definitions/uint64"
        }
      },
      "required": [
        "authority",
        "writerId",
        "workflow",
        "observationKind",
        "fields",
        "omittedFieldCount"
      ],
      "additionalProperties": false
    },
    "scheduler": {
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "sampledAt": {
              "$ref": "#/definitions/instant"
            },
            "state": {
              "const": "available"
            },
            "source": {
              "const": "web-workflow-executor"
            },
            "approximate": {
              "const": true
            },
            "lifecycle": {
              "enum": [
                "running",
                "stopping"
              ],
              "type": "string"
            },
            "activeWorkers": {
              "type": "string",
              "pattern": "^[0-2]$"
            },
            "workerLimit": {
              "type": "string",
              "pattern": "^[1-2]$"
            },
            "queuedTasks": {
              "type": "string",
              "pattern": "^(0|[1-9]|[12][0-9]|3[0-2])$"
            },
            "queueCapacity": {
              "type": "string",
              "pattern": "^([1-9]|[12][0-9]|3[0-2])$"
            }
          },
          "required": [
            "sampledAt",
            "state",
            "source",
            "approximate",
            "lifecycle",
            "activeWorkers",
            "workerLimit",
            "queuedTasks",
            "queueCapacity"
          ],
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "sampledAt": {
              "$ref": "#/definitions/instant"
            },
            "state": {
              "const": "unavailable"
            },
            "reasonCode": {
              "const": "EXTERNAL_EXECUTOR"
            }
          },
          "required": [
            "sampledAt",
            "state",
            "reasonCode"
          ],
          "additionalProperties": false
        }
      ]
    }
  },
  "oneOf": [
    {
      "type": "object",
      "properties": {
        "apiVersion": {
          "const": 1
        },
        "kind": {
          "const": "session"
        },
        "requestId": {
          "$ref": "#/definitions/requestId"
        },
        "data": {
          "$ref": "#/definitions/session"
        }
      },
      "required": [
        "apiVersion",
        "kind",
        "requestId",
        "data"
      ],
      "additionalProperties": false
    },
    {
      "type": "object",
      "properties": {
        "apiVersion": {
          "const": 1
        },
        "kind": {
          "const": "bootstrap"
        },
        "requestId": {
          "$ref": "#/definitions/requestId"
        },
        "data": {
          "$ref": "#/definitions/bootstrap"
        }
      },
      "required": [
        "apiVersion",
        "kind",
        "requestId",
        "data"
      ],
      "additionalProperties": false
    },
    {
      "type": "object",
      "properties": {
        "apiVersion": {
          "const": 1
        },
        "kind": {
          "const": "job"
        },
        "requestId": {
          "$ref": "#/definitions/requestId"
        },
        "data": {
          "$ref": "#/definitions/job"
        }
      },
      "required": [
        "apiVersion",
        "kind",
        "requestId",
        "data"
      ],
      "additionalProperties": false
    },
    {
      "type": "object",
      "properties": {
        "apiVersion": {
          "const": 1
        },
        "kind": {
          "const": "jobs"
        },
        "requestId": {
          "$ref": "#/definitions/requestId"
        },
        "data": {
          "$ref": "#/definitions/jobs"
        }
      },
      "required": [
        "apiVersion",
        "kind",
        "requestId",
        "data"
      ],
      "additionalProperties": false
    },
    {
      "type": "object",
      "properties": {
        "apiVersion": {
          "const": 1
        },
        "kind": {
          "const": "run"
        },
        "requestId": {
          "$ref": "#/definitions/requestId"
        },
        "data": {
          "$ref": "#/definitions/run"
        }
      },
      "required": [
        "apiVersion",
        "kind",
        "requestId",
        "data"
      ],
      "additionalProperties": false
    },
    {
      "type": "object",
      "properties": {
        "apiVersion": {
          "const": 1
        },
        "kind": {
          "const": "artifact"
        },
        "requestId": {
          "$ref": "#/definitions/requestId"
        },
        "data": {
          "$ref": "#/definitions/artifact"
        }
      },
      "required": [
        "apiVersion",
        "kind",
        "requestId",
        "data"
      ],
      "additionalProperties": false
    },
    {
      "type": "object",
      "properties": {
        "apiVersion": {
          "const": 1
        },
        "kind": {
          "const": "revision"
        },
        "requestId": {
          "$ref": "#/definitions/requestId"
        },
        "data": {
          "$ref": "#/definitions/revision"
        }
      },
      "required": [
        "apiVersion",
        "kind",
        "requestId",
        "data"
      ],
      "additionalProperties": false
    },
    {
      "type": "object",
      "properties": {
        "apiVersion": {
          "const": 1
        },
        "kind": {
          "const": "report"
        },
        "requestId": {
          "$ref": "#/definitions/requestId"
        },
        "data": {
          "$ref": "#/definitions/report"
        }
      },
      "required": [
        "apiVersion",
        "kind",
        "requestId",
        "data"
      ],
      "additionalProperties": false
    },
    {
      "type": "object",
      "properties": {
        "apiVersion": {
          "const": 1
        },
        "kind": {
          "const": "snapshot"
        },
        "requestId": {
          "$ref": "#/definitions/requestId"
        },
        "data": {
          "$ref": "#/definitions/snapshot"
        }
      },
      "required": [
        "apiVersion",
        "kind",
        "requestId",
        "data"
      ],
      "additionalProperties": false
    },
    {
      "type": "object",
      "properties": {
        "apiVersion": {
          "const": 1
        },
        "kind": {
          "const": "events"
        },
        "requestId": {
          "$ref": "#/definitions/requestId"
        },
        "data": {
          "$ref": "#/definitions/events"
        }
      },
      "required": [
        "apiVersion",
        "kind",
        "requestId",
        "data"
      ],
      "additionalProperties": false
    },
    {
      "type": "object",
      "properties": {
        "apiVersion": {
          "const": 1
        },
        "kind": {
          "const": "gitWorkspace"
        },
        "requestId": {
          "$ref": "#/definitions/requestId"
        },
        "data": {
          "$ref": "#/definitions/gitWorkspace"
        }
      },
      "required": [
        "apiVersion",
        "kind",
        "requestId",
        "data"
      ],
      "additionalProperties": false
    },
    {
      "type": "object",
      "properties": {
        "apiVersion": {
          "const": 1
        },
        "kind": {
          "const": "operation"
        },
        "requestId": {
          "$ref": "#/definitions/requestId"
        },
        "data": {
          "$ref": "#/definitions/operation"
        }
      },
      "required": [
        "apiVersion",
        "kind",
        "requestId",
        "data"
      ],
      "additionalProperties": false
    },
    {
      "type": "object",
      "properties": {
        "apiVersion": {
          "const": 1
        },
        "kind": {
          "const": "error"
        },
        "requestId": {
          "$ref": "#/definitions/requestId"
        },
        "error": {
          "$ref": "#/definitions/error"
        }
      },
      "required": [
        "apiVersion",
        "kind",
        "requestId",
        "error"
      ],
      "additionalProperties": false
    },
    {
      "type": "object",
      "properties": {
        "apiVersion": {
          "const": 1
        },
        "kind": {
          "const": "workflowStartRequest"
        },
        "data": {
          "$ref": "#/definitions/workflowStart"
        }
      },
      "required": [
        "apiVersion",
        "kind",
        "data"
      ],
      "additionalProperties": false
    },
    {
      "type": "object",
      "properties": {
        "apiVersion": {
          "const": 1
        },
        "kind": {
          "const": "recoverRequest"
        },
        "data": {
          "$ref": "#/definitions/recover"
        }
      },
      "required": [
        "apiVersion",
        "kind",
        "data"
      ],
      "additionalProperties": false
    },
    {
      "type": "object",
      "properties": {
        "apiVersion": {
          "const": 1
        },
        "kind": {
          "const": "gitCommitRequest"
        },
        "data": {
          "$ref": "#/definitions/gitCommit"
        }
      },
      "required": [
        "apiVersion",
        "kind",
        "data"
      ],
      "additionalProperties": false
    },
    {
      "type": "object",
      "properties": {
        "apiVersion": {
          "const": 1
        },
        "kind": {
          "const": "gitPushRequest"
        },
        "data": {
          "$ref": "#/definitions/gitPush"
        }
      },
      "required": [
        "apiVersion",
        "kind",
        "data"
      ],
      "additionalProperties": false
    },
    {
      "type": "object",
      "properties": {
        "apiVersion": {
          "const": 1
        },
        "kind": {
          "const": "sessionStartRequest"
        },
        "data": {
          "$ref": "#/definitions/sessionStart"
        }
      },
      "required": [
        "apiVersion",
        "kind",
        "data"
      ],
      "additionalProperties": false
    },
    {
      "$ref": "#/definitions/event"
    },
    {
      "type": "object",
      "properties": {
        "apiVersion": {
          "const": 1
        },
        "kind": {
          "const": "uploadProgress"
        },
        "requestId": {
          "$ref": "#/definitions/requestId"
        },
        "data": {
          "$ref": "#/definitions/uploadProgress"
        }
      },
      "required": [
        "apiVersion",
        "kind",
        "requestId",
        "data"
      ],
      "additionalProperties": false
    },
    {
      "type": "object",
      "properties": {
        "apiVersion": {
          "const": 1
        },
        "kind": {
          "const": "runs"
        },
        "requestId": {
          "$ref": "#/definitions/requestId"
        },
        "data": {
          "$ref": "#/definitions/runs"
        }
      },
      "required": [
        "apiVersion",
        "kind",
        "requestId",
        "data"
      ],
      "additionalProperties": false
    }
  ]
};
