#!/usr/bin/env node
/** Deterministic draft-07 subset generator. Unsupported schema features stop generation. */
import { createHash } from 'node:crypto';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const input = await readFile(resolve(root, 'contracts/web/v1/contract.schema.json'), 'utf8');
const schema = JSON.parse(input);
if (schema.$schema !== 'http://json-schema.org/draft-07/schema#') throw Error('Only draft-07 is supported');
const keywords = new Set(['$schema', 'title', 'description', 'definitions', '$ref', 'type',
  'properties', 'required', 'additionalProperties', 'anyOf', 'oneOf', 'allOf', 'if', 'then',
  'else', 'enum', 'const', 'pattern', 'minLength', 'maxLength', 'minimum', 'maximum', 'items',
  'minItems', 'maxItems', 'uniqueItems', 'format']);
const types = new Set(['object', 'array', 'null', 'boolean', 'string', 'number', 'integer']);
const name = (value) => ({ event: 'WebEvent', error: 'ErrorData' }[value] ?? value[0].toUpperCase() + value.slice(1));
function inspect(node) {
  if (!node || typeof node !== 'object' || Array.isArray(node)) throw Error('Expected a schema object');
  for (const key of Object.keys(node)) if (!keywords.has(key)) throw Error(`Unsupported schema keyword: ${key}`);
  if (node.type && !types.has(node.type)) throw Error('Unsupported schema type');
  if (node.format && node.format !== 'date-time') throw Error('Unsupported schema format');
  if (node.$ref && (!node.$ref.startsWith('#/definitions/') || !schema.definitions[node.$ref.slice(14)])) throw Error('Unsupported schema reference');
  if ('additionalProperties' in node && node.additionalProperties !== false) throw Error('Only closed additionalProperties is supported');
  if (node.pattern) new RegExp(node.pattern, 'u');
  for (const key of ['definitions', 'properties']) for (const child of Object.values(node[key] ?? {})) inspect(child);
  for (const key of ['anyOf', 'oneOf', 'allOf']) for (const child of node[key] ?? []) inspect(child);
  for (const key of ['items', 'if', 'then', 'else']) if (node[key]) inspect(node[key]);
}
inspect(schema);
// Runtime recursion follows data only; reject cyclic schema references before shipping a validator.
function references(node, result = new Set()) {
  if (node.$ref) result.add(node.$ref.slice(14));
  for (const child of Object.values(node.properties ?? {})) references(child, result);
  for (const key of ['anyOf', 'oneOf', 'allOf']) for (const child of node[key] ?? []) references(child, result);
  for (const key of ['items', 'if', 'then', 'else']) if (node[key]) references(node[key], result);
  return result;
}
function acyclic(key, chain = new Set()) {
  if (chain.has(key)) throw Error(`Recursive schema reference: ${key}`);
  const next = new Set([...chain, key]);
  for (const target of references(schema.definitions[key])) acyclic(target, next);
}
for (const key of Object.keys(schema.definitions)) acyclic(key);
function typeOf(node) {
  if (node.$ref) return name(node.$ref.slice(14));
  if ('const' in node) return JSON.stringify(node.const);
  if (node.enum) return node.enum.map((v) => JSON.stringify(v)).join(' | ');
  const parts = [];
  if (node.properties || node.type === 'object') {
    const members = Object.entries(node.properties ?? {}).map(([key, value]) =>
      `${JSON.stringify(key)}${node.required?.includes(key) ? '' : '?'}: ${typeOf(value)};`);
    parts.push(members.length ? `{ ${members.join(' ')} }` : 'Record<string, unknown>');
  } else if (node.type === 'array') parts.push(`Array<${typeOf(node.items ?? {})}>`);
  else if (node.type) parts.push(node.type === 'integer' ? 'number' : node.type);
  for (const key of ['oneOf', 'anyOf']) if (node[key]) parts.push(`(${node[key].map(typeOf).join(' | ')})`);
  if (node.allOf) parts.push(...node.allOf.filter((v) => !v.if).map(typeOf));
  return parts.length ? parts.map((v) => `(${v})`).join(' & ') : 'unknown';
}
const variants = schema.oneOf.filter((v) => v.properties);
const responses = variants.filter((v) => v.required.includes('requestId')).map((v) => v.properties.kind.const);
const requests = variants.filter((v) => !v.required.includes('requestId')).map((v) => v.properties.kind.const);
const hash = createHash('sha256').update(input).digest('hex');
const header = `// Generated by scripts/generate-web-api.mjs; do not edit.\n// Source SHA-256: ${hash}\n`;
const typesText = header + '// String bounds and cross-field/conditional constraints are enforced by the decoder.\n\n' +
  Object.entries(schema.definitions).map(([key, value]) => `export type ${name(key)} = ${typeOf(value)};`).join('\n\n') +
  `\n\nexport type ContractDocument = ${typeOf({oneOf: schema.oneOf})};\n` +
  `export type ResponseKind = ${responses.map((v) => JSON.stringify(v)).join(' | ')};\n` +
  `export type RequestKind = ${requests.map((v) => JSON.stringify(v)).join(' | ')};\n` +
  `export type ResponseOf<K extends ResponseKind> = Extract<ContractDocument, { kind: K }>;\n` +
  `export type RequestData<K extends RequestKind> = Extract<ContractDocument, { kind: K }>['data'];\n`;
const runtimeSchema = structuredClone(schema);
delete runtimeSchema.$schema; delete runtimeSchema.title; delete runtimeSchema.description;
const files = {
  'frontend/src/api/generated.ts': typesText,
  'frontend/src/api/generated-schema.ts': header + `import type { Schema } from './schema-types';\n\nexport const contractSchema: Schema = ${JSON.stringify(runtimeSchema, null, 2)};\n`,
};
if (process.argv.slice(2).some((arg) => arg !== '--check')) throw Error('Usage: generate-web-api.mjs [--check]');
for (const [path, contents] of Object.entries(files)) {
  const destination = resolve(root, path);
  if (process.argv.includes('--check')) {
    if (await readFile(destination, 'utf8').catch(() => null) !== contents) throw Error(`Generated contract drift: ${path}; run npm run api:generate in frontend`);
  } else {
    await mkdir(dirname(destination), {recursive: true});
    await writeFile(destination, contents);
  }
}
console.log(`Web API generated contracts ${process.argv.includes('--check') ? 'verified' : 'written'} (${hash.slice(0, 12)})`);
