package decompengine.oracle.fulltree

import decompengine.oracle.core.OracleArtifacts
import decompengine.oracle.core.OracleJson
import decompengine.oracle.core.OracleSchemas
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.LinkOption
import java.nio.file.Path
import java.nio.file.attribute.BasicFileAttributes
import java.security.MessageDigest
import java.util.Collections
import java.util.LinkedHashMap
import java.util.TreeSet
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive

/** Caller-lowerable ceilings beneath the immutable Clang capture-input v1 policy. */
data class FullTreeClangCaptureInputLimits(
    val readiness: FullTreeHeaderPlanReadinessLimits = FullTreeHeaderPlanReadinessLimits(),
    val generated: FullTreeGeneratedFileInventoryLimits = FullTreeGeneratedFileInventoryLimits(),
    val maximumActions: Int = CAPTURE_MAXIMUM_ACTIONS,
    val maximumActionPathBytes: Long = CAPTURE_MAXIMUM_ACTION_PATH_BYTES,
    val maximumArgumentBytes: Int = CAPTURE_MAXIMUM_ARGUMENT_BYTES,
    val maximumArgumentsPerAction: Int = CAPTURE_MAXIMUM_ARGUMENTS_PER_ACTION,
    val maximumBaseEnvironmentVariables: Int = CAPTURE_MAXIMUM_BASE_ENVIRONMENT_VARIABLES,
    val maximumCanonicalBytes: Int = CAPTURE_MAXIMUM_CANONICAL_BYTES,
    val maximumCaptureHeaderCandidates: Int = CAPTURE_MAXIMUM_HEADER_CANDIDATES,
    val maximumCompilerBytes: Long = CAPTURE_MAXIMUM_COMPILER_BYTES,
    val maximumEnvironmentBytes: Long = CAPTURE_MAXIMUM_ENVIRONMENT_BYTES,
    val maximumHeaderPathBytes: Long = CAPTURE_MAXIMUM_HEADER_PATH_BYTES,
    val maximumOutputRecords: Long = CAPTURE_MAXIMUM_OUTPUT_RECORDS,
    val maximumPathBytes: Int = CAPTURE_MAXIMUM_PATH_BYTES,
    val maximumPathComponentBytes: Int = CAPTURE_MAXIMUM_PATH_COMPONENT_BYTES,
    val maximumSourceOnlyUnits: Int = CAPTURE_MAXIMUM_SOURCE_ONLY_UNITS,
    val maximumTotalArgumentBytes: Long = CAPTURE_MAXIMUM_TOTAL_ARGUMENT_BYTES,
    val maximumTotalArguments: Long = CAPTURE_MAXIMUM_TOTAL_ARGUMENTS,
    val maximumWorkUnits: Long = CAPTURE_MAXIMUM_WORK_UNITS,
) {
    init {
        require(maximumActions in 1..CAPTURE_MAXIMUM_ACTIONS)
        require(maximumActionPathBytes in 1L..CAPTURE_MAXIMUM_ACTION_PATH_BYTES)
        require(maximumArgumentBytes in 1..CAPTURE_MAXIMUM_ARGUMENT_BYTES)
        require(maximumArgumentsPerAction in 11..CAPTURE_MAXIMUM_ARGUMENTS_PER_ACTION)
        require(maximumBaseEnvironmentVariables in 3..CAPTURE_MAXIMUM_BASE_ENVIRONMENT_VARIABLES)
        require(maximumCanonicalBytes in 1..CAPTURE_MAXIMUM_CANONICAL_BYTES)
        require(maximumCaptureHeaderCandidates in 1..CAPTURE_MAXIMUM_HEADER_CANDIDATES)
        require(maximumCompilerBytes in 1L..CAPTURE_MAXIMUM_COMPILER_BYTES)
        require(maximumEnvironmentBytes in 1L..CAPTURE_MAXIMUM_ENVIRONMENT_BYTES)
        require(maximumHeaderPathBytes in 1L..CAPTURE_MAXIMUM_HEADER_PATH_BYTES)
        require(maximumOutputRecords in 1L..CAPTURE_MAXIMUM_OUTPUT_RECORDS)
        require(maximumPathBytes in 1..CAPTURE_MAXIMUM_PATH_BYTES)
        require(maximumPathComponentBytes in 1..CAPTURE_MAXIMUM_PATH_COMPONENT_BYTES)
        require(maximumSourceOnlyUnits in 1..CAPTURE_MAXIMUM_SOURCE_ONLY_UNITS)
        require(maximumTotalArgumentBytes in 1L..CAPTURE_MAXIMUM_TOTAL_ARGUMENT_BYTES)
        require(maximumTotalArguments in 11L..CAPTURE_MAXIMUM_TOTAL_ARGUMENTS)
        require(maximumWorkUnits in 1L..CAPTURE_MAXIMUM_WORK_UNITS)
    }
}

/**
 * One exact, unexecuted compiler argv joined by the loader to an authenticated A13 module.
 * The exposed object and dependency paths are required operands, not an exclusive write-set claim.
 */
sealed interface FullTreeClangCaptureAction {
    val actionSha256: String
    val moduleId: String
    val unitId: String
    val shardId: String
    val sourceKind: String
    val sourcePath: String
    val workingDirectory: String
    val mainInput: String
    val arguments: List<String>
    val objectOutput: String
    val dependencyFile: String
    val traceArtifactPath: String
}

/**
 * Integrity-validated, unexecuted capture input. The name intentionally omits "authenticated":
 * compiler actions have not been replayed from Ninja and generated bytes remain unreceipted.
 */
sealed interface FullTreeClangCaptureInputRegistry {
    val artifactSha256: String
    val artifactBytes: Long
    val reportSha256: String
    val configurationSha256: String
    val captureContextSha256: String
    val captureActionsSha256: String
    val canonicalCaptureHeaderCandidateManifestSha256: String
    val actions: List<FullTreeClangCaptureAction>
    val canonicalCaptureHeaderCandidatePaths: List<String>
    val sourceOnlyUnits: List<FullTreePlanningSourceOnlyUnit>
    val baseEnvironment: Map<String, String>
    val blockerCodes: List<String>
    val canonicalBytes: ByteArray

    fun requireActionForOwnerModule(ownerUnitId: String): FullTreeClangCaptureAction
}

/** Load-only Kotlin/JVM validation. This object cannot generate, publish, rewrite, or execute actions. */
object FullTreeClangCaptureInputControl {
    val configurationSha256: String by lazy {
        OracleSchemas.configurationSha256(CAPTURE_SCHEMA, CAPTURE_CONFIGURATION_POLICY)
    }

    fun loadAndValidate(
        path: Path,
        headerPlanReadinessPath: Path,
        generatedFileInventoryPath: Path,
        sourceArchivePath: Path,
        generatedTreeArchivePath: Path,
        generatedProvenancePath: Path,
        scopePath: Path,
        sourceLockPath: Path,
        artifactManifestPath: Path,
        buildRecordPath: Path,
        inventoryPath: Path,
        sourceInventoryPath: Path,
        planningInventoryPath: Path,
        limits: FullTreeClangCaptureInputLimits = FullTreeClangCaptureInputLimits(),
    ): FullTreeClangCaptureInputRegistry = ValidatedCaptureInputRegistry.load(
        CaptureInputPaths(
            artifact = path,
            readiness = headerPlanReadinessPath,
            generatedInventory = generatedFileInventoryPath,
            sourceArchive = sourceArchivePath,
            generatedArchive = generatedTreeArchivePath,
            generatedProvenance = generatedProvenancePath,
            scope = scopePath,
            sourceLock = sourceLockPath,
            artifactManifest = artifactManifestPath,
            buildRecord = buildRecordPath,
            inventory = inventoryPath,
            sourceInventory = sourceInventoryPath,
            planningInventory = planningInventoryPath,
        ),
        limits,
    )

    private fun authenticate(
        paths: CaptureInputPaths,
        limits: FullTreeClangCaptureInputLimits,
    ): ValidatedCaptureInputState {
        requireDistinctCaptureInputs(paths)
        StableControlFile.open(
            paths.artifact,
            limits.maximumCanonicalBytes.toLong(),
            "full-tree Clang capture input",
        ).use { artifact ->
            artifact.requireSingleLink("full-tree Clang capture input")
            val (document, bytes) = readStableCaptureObject(artifact, limits)
            validateCaptureReportHash(document, limits.maximumCanonicalBytes)

            val predecessors = authenticateCapturePredecessors(paths, limits)
            val actions = validateCaptureActions(document, predecessors, limits)
            val expected = buildExpectedCaptureDocument(predecessors, actions, limits)
            if (document != expected) {
                captureFail("Clang capture input differs from its revalidated raw predecessors and actions")
            }
            if (bytes.size > limits.maximumCanonicalBytes) {
                captureFail("Clang capture input exceeds its caller-lowered canonical byte bound")
            }

            artifact.verifyUnchanged("full-tree Clang capture input")
            val terminal = authenticateCapturePredecessors(paths, limits)
            if (capturePredecessorSnapshot(terminal) != capturePredecessorSnapshot(predecessors)) {
                captureFail("Clang capture input predecessors changed during validation")
            }
            artifact.verifyUnchanged("full-tree Clang capture input")
            return validatedCaptureState(
                document,
                bytes,
                actions,
                predecessors,
            )
        }
    }

    private fun authenticateCapturePredecessors(
        paths: CaptureInputPaths,
        limits: FullTreeClangCaptureInputLimits,
    ): CapturePredecessors {
        val readiness = FullTreeHeaderPlanReadinessControl.loadAndValidate(
            paths.readiness,
            paths.sourceArchive,
            paths.scope,
            paths.sourceLock,
            paths.artifactManifest,
            paths.buildRecord,
            paths.inventory,
            paths.sourceInventory,
            paths.planningInventory,
            limits.readiness,
        )
        val generated = FullTreeGeneratedFileInventoryControl.loadAndValidate(
            paths.generatedInventory,
            paths.generatedArchive,
            paths.generatedProvenance,
            paths.scope,
            paths.sourceLock,
            paths.artifactManifest,
            paths.buildRecord,
            paths.inventory,
            paths.sourceInventory,
            paths.planningInventory,
            limits.generated,
        )
        val (planningDocument, planningBytes) = readCanonicalControlObject(
            paths.planningInventory,
            limits.generated.planning.maximumSerializedBytes,
            "full-tree planning inventory",
            "full-tree-planning-inventory",
        )
        if (OracleArtifacts.sha256(planningBytes) != readiness.planningInventoryArtifactSha256 ||
            readiness.planningInventoryArtifactSha256 != generatedPlanningArtifactSha256(
                paths.generatedInventory,
                generated,
                limits,
            )
        ) {
            captureFail("capture predecessors disagree on the planning inventory artifact")
        }
        val (generatedDocument, generatedBytes) = readCanonicalControlObject(
            paths.generatedInventory,
            limits.generated.maximumSerializedBytes,
            "full-tree generated-file inventory",
            "full-tree-generated-file-inventory",
        )
        if (OracleArtifacts.sha256(generatedBytes) != generated.artifactSha256) {
            captureFail("generated-file registry artifact changed after validation")
        }
        val generatedOracle = generatedDocument.controlObject("oracle")
        if (generatedOracle.controlString("planningInventoryArtifactSha256") !=
            readiness.planningInventoryArtifactSha256 ||
            generatedOracle.controlString("planningInventoryReportSha256") !=
            readiness.planningInventoryReportSha256 ||
            generatedOracle.controlString("planningInventoryConfigurationSha256") !=
            readiness.planningInventoryConfigurationSha256
        ) {
            captureFail("generated-file registry planning bindings do not reconcile with readiness")
        }
        val (buildRecord, buildRecordBytes) = readCanonicalControlObject(
            paths.buildRecord,
            limits.generated.planning.control.maximumBuildRecordBytes,
            "build record",
            "build-record",
        )
        val buildRecordSha256 = OracleArtifacts.sha256(buildRecordBytes)
        val planningOracle = planningDocument.controlObject("oracle")
        if (planningOracle.controlString("buildRecordSha256") != buildRecordSha256 ||
            generatedOracle.controlString("buildRecordSha256") != buildRecordSha256
        ) {
            captureFail("capture predecessor build-record commitments do not reconcile")
        }
        val context = expectedCaptureContext(
            readiness,
            generated,
            planningDocument,
            buildRecord,
            buildRecordSha256,
            generatedDocument,
            limits,
        )
        return CapturePredecessors(readiness, generated, context)
    }

    private fun generatedPlanningArtifactSha256(
        generatedInventoryPath: Path,
        generated: FullTreeGeneratedFileRegistry,
        limits: FullTreeClangCaptureInputLimits,
    ): String {
        val (document, bytes) = readCanonicalControlObject(
            generatedInventoryPath,
            limits.generated.maximumSerializedBytes,
            "full-tree generated-file inventory",
            "full-tree-generated-file-inventory",
        )
        if (OracleArtifacts.sha256(bytes) != generated.artifactSha256) {
            captureFail("generated-file registry artifact changed after validation")
        }
        return document.controlObject("oracle").controlString("planningInventoryArtifactSha256")
    }

    private fun expectedCaptureContext(
        readiness: AuthenticatedFullTreeHeaderPlanReadiness,
        generated: FullTreeGeneratedFileRegistry,
        planningDocument: JsonObject,
        buildRecord: JsonObject,
        buildRecordSha256: String,
        generatedDocument: JsonObject,
        limits: FullTreeClangCaptureInputLimits,
    ): CaptureExpectedContext {
        if (readiness.sourceModules.size !in 1..limits.maximumActions) {
            captureFail("authenticated A13 module population exceeds the capture action bound")
        }
        if (readiness.sourceOnlyUnits.size > limits.maximumSourceOnlyUnits) {
            captureFail("source-only population exceeds the capture bound")
        }
        val directories = buildRecord.controlObject("directories")
        val sourceRoot = requireCaptureAbsolutePath(
            directories.controlString("source"),
            "build-record source root",
            limits,
        )
        val buildRoot = requireCaptureAbsolutePath(
            directories.controlString("build"),
            "build-record build root",
            limits,
        )
        val installRoot = requireCaptureAbsolutePath(
            directories.controlString("install"),
            "build-record install root",
            limits,
        )
        requireDisjointCaptureRoots(sourceRoot, buildRoot, installRoot)

        val commands = buildRecord.controlObject("commands")
        val configure = commands.controlArray("configure")
        val cDriver = configuredDriver(configure, "-DCMAKE_C_COMPILER=", "C compiler", limits)
        val cxxDriver = configuredDriver(configure, "-DCMAKE_CXX_COMPILER=", "C++ compiler", limits)
        val compilerTool = buildRecord.controlArray("tools").controlObjects("build-record tools")
            .singleOrNull { it.controlString("role") == "compiler" }
            ?: captureFail("build record must contain exactly one compiler tool")
        val compilerBinding = captureToolBinding(compilerTool, "compiler", limits.maximumCompilerBytes)
        if (compilerBinding.controlString("path") != cDriver) {
            captureFail("recorded compiler identity does not bind the configured C driver")
        }
        val compilerIdentity = captureCanonicalCommitment(CAPTURE_COMPILER_IDENTITY_DOMAIN, compilerBinding)

        val variables = buildRecord.controlObject("environment").controlObject("variables")
        val environment = captureEnvironment(variables, limits)
        val container = buildRecord.controlObject("environment").controlObject("container")
        val generatedBuildGraph = generatedDocument.controlObject("provenance").controlObject("buildGraph")
        val expectedBuild = captureBuildDocument(
            sourceRoot,
            buildRoot,
            installRoot,
            container,
            commands,
            generatedBuildGraph,
            buildRecordSha256,
        )

        val sourceHeaders = readiness.authenticatedSourceHeaderCandidatePaths
        val generatedHeaders = generated.canonicalGeneratedHeaderPaths
        val captureHeaders = TreeSet<String>(FULL_TREE_CODE_POINT_ORDER)
        var headerPathBytes = 0L
        (sourceHeaders + generatedHeaders).forEach { path ->
            requireCaptureHeaderCandidatePath(path, limits)
            headerPathBytes = captureAddExact(
                headerPathBytes,
                path.toByteArray(StandardCharsets.UTF_8).size.toLong(),
                "capture header-path byte",
            )
            if (headerPathBytes > limits.maximumHeaderPathBytes) {
                captureFail("capture header candidate paths exceed their aggregate byte bound")
            }
            if (!captureHeaders.add(path)) captureFail("capture header candidate population overlaps")
        }
        if (captureHeaders.size > limits.maximumCaptureHeaderCandidates) {
            captureFail("capture header candidate population exceeds its bound")
        }

        val modules = readiness.sourceModules.map { module ->
            val physicalInput = captureModuleInput(module, sourceRoot, buildRoot, limits)
            CaptureModule(
                module.moduleId,
                module.unitId,
                module.shardId,
                module.sourceKind,
                module.sourcePath,
                physicalInput,
            )
        }
        if (modules.map(CaptureModule::unitId).toSet().size != modules.size ||
            modules.map(CaptureModule::sourcePath).toSet().size != modules.size ||
            modules.map(CaptureModule::mainInput).toSet().size != modules.size
        ) {
            captureFail("authenticated A13 module identities do not form an exact capture population")
        }
        reconcileGeneratedModules(modules, generated)

        val planningOracle = planningDocument.controlObject("oracle")
        val generatedCounts = generatedDocument.controlObject("counts")
        val oracleDocument = JsonObject(
            mapOf(
                "artifactManifestSha256" to planningOracle.getValue("artifactManifestSha256"),
                "buildRecordSha256" to JsonPrimitive(buildRecordSha256),
                "configurationSha256" to JsonPrimitive(configurationSha256),
                "generatedFileInventoryArtifactBytes" to JsonPrimitive(generated.artifactBytes),
                "generatedFileInventoryArtifactSha256" to JsonPrimitive(generated.artifactSha256),
                "generatedFileInventoryConfigurationSha256" to JsonPrimitive(generated.configurationSha256),
                "generatedFileInventoryReportSha256" to JsonPrimitive(generated.reportSha256),
                "headerPlanReadinessArtifactBytes" to JsonPrimitive(readiness.artifactBytes),
                "headerPlanReadinessArtifactSha256" to JsonPrimitive(readiness.artifactSha256),
                "headerPlanReadinessConfigurationSha256" to JsonPrimitive(readiness.configurationSha256),
                "headerPlanReadinessReportSha256" to JsonPrimitive(readiness.reportSha256),
                "id" to buildRecord.controlObject("oracle").getValue("id"),
                "inventoryArtifactSha256" to planningOracle.getValue("inventoryArtifactSha256"),
                "planningInventoryArtifactSha256" to JsonPrimitive(readiness.planningInventoryArtifactSha256),
                "planningInventoryConfigurationSha256" to JsonPrimitive(
                    readiness.planningInventoryConfigurationSha256,
                ),
                "planningInventoryReportSha256" to JsonPrimitive(readiness.planningInventoryReportSha256),
                "scopeSha256" to planningOracle.getValue("scopeSha256"),
                "sourceInventoryArtifactSha256" to planningOracle.getValue("sourceInventoryArtifactSha256"),
                "sourceLockSha256" to planningOracle.getValue("sourceLockSha256"),
            ),
        )
        val sourceDocument = JsonObject(
            mapOf(
                "archiveSha256" to JsonPrimitive(readiness.sourceArchiveSha256),
                "dependencyArtifactSha256" to JsonPrimitive(readiness.sourceDependencyArtifactSha256),
                "dependencyConfigurationSha256" to JsonPrimitive(
                    readiness.sourceDependencyConfigurationSha256,
                ),
                "dependencyReportSha256" to JsonPrimitive(readiness.sourceDependencyReportSha256),
                "headerCandidateManifestSha256" to JsonPrimitive(readiness.sourceHeaderManifestSha256),
                "headerCandidates" to JsonPrimitive(sourceHeaders.size),
            ),
        )
        val generatedDocumentSummary = JsonObject(
            mapOf(
                "archiveSha256" to JsonPrimitive(generated.archiveSha256),
                "buildGraphProvenanceSha256" to JsonPrimitive(generated.buildGraphProvenanceSha256),
                "canonicalFileManifestSha256" to JsonPrimitive(generated.canonicalGeneratedFileManifestSha256),
                "canonicalHeaderManifestSha256" to JsonPrimitive(
                    generated.canonicalGeneratedHeaderManifestSha256,
                ),
                "files" to JsonPrimitive(generated.generatedFiles.size),
                "generationReceiptBound" to JsonPrimitive(false),
                "headers" to JsonPrimitive(generated.generatedHeaders.size),
                "provenanceSha256" to JsonPrimitive(generated.provenanceSha256),
                "snapshotBytesAuthenticated" to JsonPrimitive(false),
                "snapshotBytesIntegrityVerified" to JsonPrimitive(true),
                "translationUnits" to JsonPrimitive(generated.generatedTranslationUnits.size),
            ),
        )
        if (generatedCounts.controlLong("generatedFiles") != generated.generatedFiles.size.toLong() ||
            generatedCounts.controlLong("generatedHeaders") != generated.generatedHeaders.size.toLong() ||
            generatedCounts.controlLong("generatedTranslationUnits") !=
            generated.generatedTranslationUnits.size.toLong()
        ) {
            captureFail("generated-file registry public population differs from its artifact")
        }
        val compilerDocument = JsonObject(
            mapOf(
                "cDriverPath" to JsonPrimitive(cDriver),
                "cxxDriverIdentityAuthenticated" to JsonPrimitive(false),
                "cxxDriverPath" to JsonPrimitive(cxxDriver),
                "recordedTool" to compilerBinding,
                "recordedToolIdentitySha256" to JsonPrimitive(compilerIdentity),
            ),
        )
        val headerManifestSha256 = CaptureCommitment(CAPTURE_HEADER_MANIFEST_DOMAIN).apply {
            long(captureHeaders.size.toLong())
            captureHeaders.forEach { path -> token(path.toByteArray(StandardCharsets.UTF_8)) }
        }.finish()
        val captureContextSha256 = captureCanonicalCommitment(
            CAPTURE_CONTEXT_DOMAIN,
            captureContextDocument(
                oracleDocument,
                sourceDocument,
                generatedDocumentSummary,
                compilerDocument,
                expectedBuild,
                environment.document,
                headerManifestSha256,
            ),
        )
        return CaptureExpectedContext(
            planningDocument = planningDocument,
            buildRecord = buildRecord,
            buildRecordSha256 = buildRecordSha256,
            generatedInventoryDocument = generatedDocument,
            oracleDocument = oracleDocument,
            sourceDocument = sourceDocument,
            generatedDocument = generatedDocumentSummary,
            compilerDocument = compilerDocument,
            buildDocument = expectedBuild,
            environmentDocument = environment.document,
            baseEnvironment = environment.variables,
            baseEnvironmentSha256 = environment.sha256,
            environmentBytes = environment.bytes,
            captureContextSha256 = captureContextSha256,
            headerManifestSha256 = headerManifestSha256,
            buildRoot = buildRoot,
            cDriver = cDriver,
            cxxDriver = cxxDriver,
            sourceArchiveSha256 = readiness.sourceArchiveSha256,
            modules = modules,
            sourceOnlyUnits = readiness.sourceOnlyUnits,
            sourceHeaderCount = sourceHeaders.size,
            generatedHeaderCount = generatedHeaders.size,
            headerPaths = Collections.unmodifiableList(ArrayList(captureHeaders)),
            headerPathBytes = headerPathBytes,
            generatedTranslationUnits = generated.generatedTranslationUnits.associateBy { it.unitId },
        )
    }

    private fun captureEnvironment(
        variables: JsonObject,
        limits: FullTreeClangCaptureInputLimits,
    ): CaptureEnvironment {
        if (variables.size !in 3..limits.maximumBaseEnvironmentVariables) {
            captureFail("build-record base environment exceeds the capture variable bound")
        }
        val records = variables.entries.map { (name, rawValue) ->
            if (!name.matches(CAPTURE_ENVIRONMENT_NAME) ||
                CAPTURE_FORBIDDEN_ENVIRONMENT_PREFIXES.any(name::startsWith) ||
                name in CAPTURE_FORBIDDEN_ENVIRONMENT_NAMES
            ) {
                captureFail("build-record base environment contains a forbidden capture variable")
            }
            val value = (rawValue as? JsonPrimitive)?.takeIf { it.isString }?.content
                ?: captureFail("build-record base environment value is not a string")
            if ('\u0000' in value) {
                captureFail("build-record base environment contains a NUL value")
            }
            JsonObject(mapOf("name" to JsonPrimitive(name), "value" to JsonPrimitive(value)))
        }.sortedWith(compareBy(FULL_TREE_CODE_POINT_ORDER) { it.controlString("name") })
        if (records.map { it.controlString("name") }.toSet().size != records.size) {
            captureFail("build-record base environment duplicates a variable")
        }
        var environmentBytes = 0L
        val retained = LinkedHashMap<String, String>()
        records.forEach { record ->
            val name = record.controlString("name")
            val value = record.controlString("value")
            environmentBytes = captureAddExact(
                environmentBytes,
                name.toByteArray(StandardCharsets.UTF_8).size.toLong(),
                "capture environment byte",
            )
            environmentBytes = captureAddExact(
                environmentBytes,
                value.toByteArray(StandardCharsets.UTF_8).size.toLong(),
                "capture environment byte",
            )
            if (environmentBytes > limits.maximumEnvironmentBytes) {
                captureFail("build-record base environment exceeds its byte bound")
            }
            retained[name] = value
        }
        val recordsArray = JsonArray(records)
        val sha256 = captureCanonicalCommitment(CAPTURE_ENVIRONMENT_DOMAIN, recordsArray)
        return CaptureEnvironment(
            document = JsonObject(
                mapOf(
                    "baseEnvironmentSha256" to JsonPrimitive(sha256),
                    "baseVariables" to recordsArray,
                    "fixedCaptureVariables" to CAPTURE_FIXED_ENVIRONMENT,
                    "inheritedEnvironment" to JsonPrimitive("cleared"),
                    "perActionHeaderOutput" to CAPTURE_PER_ACTION_ENVIRONMENT,
                ),
            ),
            variables = Collections.unmodifiableMap(retained),
            sha256 = sha256,
            bytes = environmentBytes,
        )
    }

    private fun captureBuildDocument(
        sourceRoot: String,
        buildRoot: String,
        installRoot: String,
        container: JsonObject,
        commands: JsonObject,
        generatedBuildGraph: JsonObject,
        buildRecordSha256: String,
    ): JsonObject {
        if (generatedBuildGraph.controlString("buildRecordSha256") != buildRecordSha256 ||
            generatedBuildGraph.controlString("buildDirectory") != buildRoot ||
            generatedBuildGraph.controlString("buildSystem") != "cmake-ninja"
        ) {
            captureFail("generated build graph does not reconcile with the capture build record")
        }
        val configureSha256 = fullTreeGeneratedConfigureCommandSha256(commands.controlArray("configure"))
        val compileSha256 = fullTreeGeneratedCompileCommandSha256(commands.controlArray("compile"))
        if (generatedBuildGraph.controlString("configureCommandSha256") != configureSha256 ||
            generatedBuildGraph.controlString("compileCommandSha256") != compileSha256
        ) {
            captureFail("generated build graph command commitments do not reconcile")
        }
        return JsonObject(
            mapOf(
                "buildDirectory" to JsonPrimitive(buildRoot),
                "cmakeCacheBytes" to generatedBuildGraph.getValue("cmakeCacheBytes"),
                "cmakeCacheSha256" to generatedBuildGraph.getValue("cmakeCacheSha256"),
                "cmakeTool" to generatedBuildGraph.getValue("cmakeTool"),
                "compileCommandSha256" to JsonPrimitive(compileSha256),
                "configureCommandSha256" to JsonPrimitive(configureSha256),
                "containerDigest" to container.getValue("digest"),
                "containerImage" to container.getValue("image"),
                "installDirectory" to JsonPrimitive(installRoot),
                "ninjaManifestBytes" to generatedBuildGraph.getValue("ninjaManifestBytes"),
                "ninjaManifestSha256" to generatedBuildGraph.getValue("ninjaManifestSha256"),
                "ninjaTool" to generatedBuildGraph.getValue("ninjaTool"),
                "platform" to container.getValue("platform"),
                "sourceDateEpoch" to generatedBuildGraph.getValue("sourceDateEpoch"),
                "sourceDirectory" to JsonPrimitive(sourceRoot),
            ),
        )
    }

    private fun configuredDriver(
        configure: JsonArray,
        prefix: String,
        label: String,
        limits: FullTreeClangCaptureInputLimits,
    ): String {
        val matches = configure.map { value -> value.controlString("configure command") }
            .filter { it.startsWith(prefix) }
        if (matches.size != 1) captureFail("build record must configure exactly one $label path")
        val path = matches.single().removePrefix(prefix)
        return requireCaptureAbsolutePath(path, "configured $label", limits)
    }

    private fun captureToolBinding(
        tool: JsonObject,
        expectedRole: String,
        maximumBytes: Long,
    ): JsonObject {
        val path = tool.controlString("path")
        val versionCommand = tool.controlArray("versionCommand")
        if (versionCommand.firstOrNull()?.controlString("compiler version command") != path) {
            captureFail("$expectedRole version command does not start with its executable path")
        }
        val executableBytes = tool.controlLong("executableBytes")
        if (executableBytes !in 1L..maximumBytes) {
            captureFail("$expectedRole executable exceeds the capture tool byte bound")
        }
        return JsonObject(
            mapOf(
                "executableBytes" to JsonPrimitive(executableBytes),
                "executableSha256" to JsonPrimitive(tool.controlString("executableSha256")),
                "path" to JsonPrimitive(path),
                "role" to JsonPrimitive(expectedRole),
                "versionOutputSha256" to JsonPrimitive(
                    OracleArtifacts.sha256(tool.controlString("versionOutput").toByteArray(StandardCharsets.UTF_8)),
                ),
            ),
        )
    }

    private fun captureModuleInput(
        module: FullTreePlanningSourceModule,
        sourceRoot: String,
        buildRoot: String,
        limits: FullTreeClangCaptureInputLimits,
    ): String {
        if (module.moduleId != module.unitId || !module.unitId.matches(CAPTURE_COMPILATION_UNIT_ID)) {
            captureFail("capture module has an invalid A13 identity")
        }
        val (prefix, root) = when (module.sourceKind) {
            "handwritten" -> "source/" to sourceRoot
            "generated" -> "generated/" to buildRoot
            else -> captureFail("capture module has an unsupported source kind")
        }
        if (!module.sourcePath.startsWith(prefix)) {
            captureFail("capture module path differs from its source kind")
        }
        val suffix = module.sourcePath.removePrefix(prefix)
        requireCaptureRelativePath(suffix, "capture module source", limits)
        return "$root/$suffix"
    }

    private fun reconcileGeneratedModules(
        modules: List<CaptureModule>,
        generated: FullTreeGeneratedFileRegistry,
    ) {
        val generatedModules = modules.filter { it.sourceKind == "generated" }
        if (generatedModules.size != generated.generatedTranslationUnits.size) {
            captureFail("generated capture action population differs from the generated-file registry")
        }
        generatedModules.forEach { module ->
            val byOwner = generated.requireGeneratedTranslationUnit(module.unitId)
            val byPath = generated.requireGeneratedFile(module.sourcePath)
            if (byPath !is FullTreeGeneratedTranslationUnit || byPath != byOwner ||
                byOwner.moduleId != module.moduleId || byOwner.unitId != module.unitId ||
                byOwner.shardId != module.shardId || byOwner.sourcePath != module.sourcePath
            ) {
                captureFail("generated capture module does not reconcile with its generated-file identity")
            }
        }
    }

    private fun validateCaptureActions(
        document: JsonObject,
        predecessors: CapturePredecessors,
        limits: FullTreeClangCaptureInputLimits,
    ): ValidatedCaptureActions {
        val context = predecessors.context
        val rawActions = document.controlArray("actions").controlObjects("Clang capture actions")
        if (rawActions.size != context.modules.size || rawActions.size > limits.maximumActions) {
            captureFail("Clang capture actions do not cover the authenticated A13 module population exactly")
        }
        val objectOutputs = HashSet<String>()
        val dependencyFiles = HashSet<String>()
        var argumentCount = 0L
        var argumentBytes = 0L
        var actionPathBytes = 0L
        val actions = ArrayList<ValidatedClangCaptureAction>(rawActions.size)

        rawActions.forEachIndexed { index, action ->
            val module = context.modules[index]
            val workingDirectory = action.controlString("workingDirectory")
            val mainInput = action.controlString("mainInput")
            requireCaptureAbsolutePath(workingDirectory, "capture action working directory", limits)
            requireCaptureAbsolutePath(mainInput, "capture action main input", limits)
            if (workingDirectory != context.buildRoot || mainInput != module.mainInput) {
                captureFail("capture action order or physical module mapping differs from authenticated A13")
            }
            val rawArguments = action.controlArray("arguments")
            if (rawArguments.size !in 11..limits.maximumArgumentsPerAction) {
                captureFail("capture action argument population exceeds its bound")
            }
            argumentCount = captureAddExact(
                argumentCount,
                rawArguments.size.toLong(),
                "capture argument",
            )
            if (argumentCount > limits.maximumTotalArguments) {
                captureFail("capture action population exceeds its aggregate argument bound")
            }
            val arguments = rawArguments.map { value ->
                val argument = value.controlString("capture argument")
                val bytes = argument.toByteArray(StandardCharsets.UTF_8).size
                if (argument.isEmpty() || bytes > limits.maximumArgumentBytes ||
                    argument.any { it == '\u0000' || it == '\r' || it == '\n' }
                ) {
                    captureFail("capture argument violates its canonical byte profile")
                }
                argumentBytes = captureAddExact(argumentBytes, bytes.toLong(), "capture argument byte")
                if (argumentBytes > limits.maximumTotalArgumentBytes) {
                    captureFail("capture action population exceeds its aggregate argument-byte bound")
                }
                argument
            }
            val validated = validateCaptureCommand(
                module,
                workingDirectory,
                mainInput,
                arguments,
                context,
                limits,
            )
            if (!objectOutputs.add(validated.objectOutput) ||
                !dependencyFiles.add(validated.dependencyFile) ||
                validated.objectOutput in dependencyFiles ||
                validated.dependencyFile in objectOutputs
            ) {
                captureFail("capture actions collide on an object or dependency output")
            }
            listOf(workingDirectory, mainInput, validated.objectOutput, validated.dependencyFile).forEach { path ->
                actionPathBytes = captureAddExact(
                    actionPathBytes,
                    path.toByteArray(StandardCharsets.UTF_8).size.toLong(),
                    "capture action-path byte",
                )
                if (actionPathBytes > limits.maximumActionPathBytes) {
                    captureFail("capture action paths exceed their aggregate byte bound")
                }
            }
            actions += validated
        }
        val expectedUnits = context.modules.map(CaptureModule::unitId).toSet()
        if (actions.map(ValidatedClangCaptureAction::unitId).toSet() != expectedUnits) {
            captureFail("capture action owner coverage differs from authenticated A13")
        }
        val actionsSha256 = CaptureCommitment(CAPTURE_ACTION_MANIFEST_DOMAIN).apply {
            long(actions.size.toLong())
            actions.forEach { action -> token(action.actionSha256.toByteArray(StandardCharsets.US_ASCII)) }
        }.finish()
        return ValidatedCaptureActions(
            documents = rawActions,
            actions = Collections.unmodifiableList(actions),
            actionsSha256 = actionsSha256,
            argumentCount = argumentCount,
            argumentBytes = argumentBytes,
            actionPathBytes = actionPathBytes,
        )
    }

    private fun validateCaptureCommand(
        module: CaptureModule,
        workingDirectory: String,
        mainInput: String,
        arguments: List<String>,
        context: CaptureExpectedContext,
        limits: FullTreeClangCaptureInputLimits,
    ): ValidatedClangCaptureAction {
        val expectedDriver = when {
            module.sourcePath.endsWith(".c") || module.sourcePath.endsWith(".S") -> context.cDriver
            module.sourcePath.endsWith(".cpp") -> context.cxxDriver
            else -> captureFail("capture module has an unsupported compiler-driver suffix")
        }
        if (arguments.firstOrNull() != expectedDriver) {
            captureFail("capture action does not start with its configured language driver")
        }
        if (arguments.size < CAPTURE_COMPILE_FRAME_SIZE ||
            arguments[1] != "--no-default-config" ||
            arguments[2] != "-MD" ||
            arguments[3] != "-MT" ||
            arguments[5] != "-MF" ||
            arguments[7] != "-o" ||
            arguments[9] != "-c" ||
            arguments[10] != mainInput
        ) {
            captureFail("capture action does not use the fixed compiler-frame grammar")
        }
        if (arguments.count { it == "--no-default-config" } != 1 ||
            arguments.count { it == "-MD" } != 1 ||
            arguments.count { it == "-c" } != 1 ||
            arguments.count { it == mainInput } != 1
        ) {
            captureFail("capture action duplicates a fixed compiler-frame token")
        }
        if (arguments.drop(CAPTURE_COMPILE_FRAME_SIZE).any { !it.startsWith('-') }) {
            captureFail("capture action tail must contain only dash-prefixed tokens")
        }
        val usesIndirectArguments = arguments.any { argument ->
            argument.startsWith('@') || argument.startsWith("--config")
        }
        if (usesIndirectArguments) {
            captureFail("capture action response and compiler-config files are forbidden")
        }
        val usesOpaqueForwarding = arguments.any { argument ->
            CAPTURE_OPAQUE_FORWARDING_PREFIXES.any(argument::startsWith)
        }
        if (usesOpaqueForwarding) {
            captureFail("capture action opaque compiler forwarding is forbidden")
        }
        if (arguments.any { it.startsWith("-x") }) {
            captureFail("capture action language overrides are forbidden")
        }
        if (arguments.any { it in CAPTURE_FORBIDDEN_ARGUMENTS }) {
            captureFail("capture action contains a forbidden non-compiling or mutating mode")
        }
        CAPTURE_CAPTURE_OPTION_PREFIXES.forEach { prefix ->
            if (arguments.any { it == prefix || it.startsWith("$prefix=") }) {
                captureFail("capture action must not author the host-owned header-capture overlay")
            }
        }
        val target = requireCaptureOption(arguments, "-MT")
        val depfileRaw = requireCaptureOption(arguments, "-MF")
        val outputRaw = requireCaptureOption(arguments, "-o")
        if (target != outputRaw || depfileRaw != "$outputRaw.d") {
            captureFail("capture action target, object, and dependency-file operands do not reconcile")
        }
        val objectOutput = resolveCaptureBuildOutput(workingDirectory, outputRaw, context.buildRoot, limits)
        val dependencyFile = resolveCaptureBuildOutput(workingDirectory, depfileRaw, context.buildRoot, limits)
        if (objectOutput == dependencyFile) captureFail("capture object and dependency outputs overlap")

        val generatedEvidence = if (module.sourceKind == "generated") {
            context.generatedTranslationUnits[module.unitId]
                ?: captureFail("generated capture action has no generated-file evidence")
        } else {
            null
        }
        val actionSha256 = CaptureCommitment(CAPTURE_ACTION_DOMAIN).apply {
            token(configurationSha256.toByteArray(StandardCharsets.US_ASCII))
            token(context.captureContextSha256.toByteArray(StandardCharsets.US_ASCII))
            token(context.buildRecordSha256.toByteArray(StandardCharsets.US_ASCII))
            token(context.baseEnvironmentSha256.toByteArray(StandardCharsets.US_ASCII))
            token(module.moduleId.toByteArray(StandardCharsets.UTF_8))
            token(module.unitId.toByteArray(StandardCharsets.UTF_8))
            token(module.shardId.toByteArray(StandardCharsets.UTF_8))
            token(module.sourceKind.toByteArray(StandardCharsets.UTF_8))
            token(module.sourcePath.toByteArray(StandardCharsets.UTF_8))
            if (generatedEvidence == null) {
                token("source-archive".toByteArray(StandardCharsets.US_ASCII))
                token(context.sourceArchiveSha256.toByteArray(StandardCharsets.US_ASCII))
            } else {
                token("generated-file".toByteArray(StandardCharsets.US_ASCII))
                long(generatedEvidence.bytes)
                token(generatedEvidence.sha256.toByteArray(StandardCharsets.US_ASCII))
                token(generatedEvidence.generatorActionSha256.toByteArray(StandardCharsets.US_ASCII))
            }
            token(workingDirectory.toByteArray(StandardCharsets.UTF_8))
            token(mainInput.toByteArray(StandardCharsets.UTF_8))
            long(arguments.size.toLong())
            arguments.forEach { argument -> token(argument.toByteArray(StandardCharsets.UTF_8)) }
            token(objectOutput.toByteArray(StandardCharsets.UTF_8))
            token(dependencyFile.toByteArray(StandardCharsets.UTF_8))
        }.finish()
        return ValidatedClangCaptureAction(
            actionSha256 = actionSha256,
            moduleId = module.moduleId,
            unitId = module.unitId,
            shardId = module.shardId,
            sourceKind = module.sourceKind,
            sourcePath = module.sourcePath,
            workingDirectory = workingDirectory,
            mainInput = mainInput,
            arguments = Collections.unmodifiableList(ArrayList(arguments)),
            objectOutput = objectOutput,
            dependencyFile = dependencyFile,
            traceArtifactPath = "traces/$actionSha256.json",
        )
    }

    private fun requireCaptureOption(arguments: List<String>, option: String): String {
        if (arguments.any { argument -> argument != option && argument.startsWith(option) }) {
            captureFail("capture action uses a joined or ambiguous $option option")
        }
        val indexes = arguments.indices.filter { arguments[it] == option }
        if (indexes.size != 1 || indexes.single() == arguments.lastIndex) {
            captureFail("capture action must contain exactly one separate $option operand")
        }
        val value = arguments[indexes.single() + 1]
        if (value == "-" || value.startsWith('-')) {
            captureFail("capture action $option output is invalid")
        }
        return value
    }

    private fun resolveCaptureBuildOutput(
        workingDirectory: String,
        raw: String,
        buildRoot: String,
        limits: FullTreeClangCaptureInputLimits,
    ): String {
        val resolved = if (raw.startsWith('/')) {
            requireCaptureAbsolutePath(raw, "capture output", limits)
        } else {
            requireCaptureRelativePath(raw, "capture output", limits)
            "$workingDirectory/$raw"
        }
        if (!resolved.startsWith("$buildRoot/")) {
            captureFail("capture output escapes the authenticated build-root namespace")
        }
        return resolved
    }

    private fun buildExpectedCaptureDocument(
        predecessors: CapturePredecessors,
        actions: ValidatedCaptureActions,
        limits: FullTreeClangCaptureInputLimits,
    ): JsonObject {
        val context = predecessors.context
        val actionCount = actions.actions.size.toLong()
        val headerCount = context.headerPaths.size.toLong()
        val sourceOnlyCount = context.sourceOnlyUnits.size.toLong()
        val environmentCount = context.baseEnvironment.size.toLong()
        val outputRecords = listOf(
            actionCount,
            headerCount,
            sourceOnlyCount,
            environmentCount,
            CAPTURE_BLOCKERS.size.toLong(),
        ).fold(0L) { total, value -> captureAddExact(total, value, "capture output record") }
        if (outputRecords > limits.maximumOutputRecords) {
            captureFail("capture input exceeds its caller-lowered output-record bound")
        }
        val workUnits = listOf(
            64L,
            captureMultiplyExact(12L, actionCount, "capture action work-unit"),
            captureMultiplyExact(4L, actions.argumentCount, "capture argument work-unit"),
            captureMultiplyExact(3L, headerCount, "capture header work-unit"),
            captureMultiplyExact(2L, sourceOnlyCount, "capture source-only work-unit"),
            captureMultiplyExact(2L, environmentCount, "capture environment work-unit"),
            captureMultiplyExact(2L, CAPTURE_BLOCKERS.size.toLong(), "capture blocker work-unit"),
        ).fold(0L) { total, value -> captureAddExact(total, value, "capture work-unit") }
        if (workUnits > limits.maximumWorkUnits) {
            captureFail("capture input exceeds its caller-lowered work-unit bound")
        }
        val withoutHash = JsonObject(
            mapOf(
                "acpBoundary" to CAPTURE_ACP_BOUNDARY,
                "actions" to JsonArray(actions.documents),
                "authority" to CAPTURE_AUTHORITY,
                "blockerDispositions" to JsonArray(CAPTURE_BLOCKER_DISPOSITIONS),
                "blockers" to JsonArray(CAPTURE_BLOCKERS),
                "bounds" to CAPTURE_BOUNDS,
                "build" to context.buildDocument,
                "canonicalCaptureHeaderCandidatePaths" to JsonArray(
                    context.headerPaths.map(::JsonPrimitive),
                ),
                "capturePolicy" to CAPTURE_POLICY,
                "commitments" to JsonObject(
                    mapOf(
                        "actionsSha256" to JsonPrimitive(actions.actionsSha256),
                        "captureContextSha256" to JsonPrimitive(context.captureContextSha256),
                        "canonicalCaptureHeaderCandidateManifestSha256" to JsonPrimitive(
                            context.headerManifestSha256,
                        ),
                    ),
                ),
                "compiler" to context.compilerDocument,
                "counts" to JsonObject(
                    mapOf(
                        "actionPathBytes" to JsonPrimitive(actions.actionPathBytes),
                        "actions" to JsonPrimitive(actions.actions.size),
                        "argumentBytes" to JsonPrimitive(actions.argumentBytes),
                        "arguments" to JsonPrimitive(actions.argumentCount),
                        "baseEnvironmentVariables" to JsonPrimitive(context.baseEnvironment.size),
                        "blockers" to JsonPrimitive(CAPTURE_BLOCKERS.size),
                        "captureHeaderCandidates" to JsonPrimitive(context.headerPaths.size),
                        "environmentBytes" to JsonPrimitive(context.environmentBytes),
                        "generatedActions" to JsonPrimitive(
                            context.modules.count { it.sourceKind == "generated" },
                        ),
                        "generatedHeaderCandidates" to JsonPrimitive(context.generatedHeaderCount),
                        "handwrittenActions" to JsonPrimitive(
                            context.modules.count { it.sourceKind == "handwritten" },
                        ),
                        "headerPathBytes" to JsonPrimitive(context.headerPathBytes),
                        "outputRecords" to JsonPrimitive(outputRecords),
                        "sourceHeaderCandidates" to JsonPrimitive(context.sourceHeaderCount),
                        "sourceModules" to JsonPrimitive(context.modules.size),
                        "sourceOnlyUnits" to JsonPrimitive(context.sourceOnlyUnits.size),
                        "workUnits" to JsonPrimitive(workUnits),
                    ),
                ),
                "environment" to context.environmentDocument,
                "generated" to context.generatedDocument,
                "kind" to JsonPrimitive("full-tree-clang-capture-input-v1"),
                "oracle" to context.oracleDocument,
                "schemaVersion" to JsonPrimitive(1),
                "source" to context.sourceDocument,
            ),
        )
        val reportSha256 = OracleArtifacts.sha256(
            OracleJson.canonicalBytes(withoutHash, controlJsonLimits(CAPTURE_MAXIMUM_CANONICAL_BYTES)),
        )
        val expected = JsonObject(withoutHash + ("reportSha256" to JsonPrimitive(reportSha256)))
        val (_, bytes) = snapshotControlObject(
            expected,
            limits.maximumCanonicalBytes,
            "full-tree Clang capture input",
            CAPTURE_SCHEMA,
        )
        if (bytes.size > limits.maximumCanonicalBytes) {
            captureFail("capture input exceeds its caller-lowered canonical byte bound")
        }
        return expected
    }

    private fun validatedCaptureState(
        document: JsonObject,
        bytes: ByteArray,
        actions: ValidatedCaptureActions,
        predecessors: CapturePredecessors,
    ): ValidatedCaptureInputState = ValidatedCaptureInputState(
        artifactSha256 = OracleArtifacts.sha256(bytes),
        artifactBytes = bytes.size.toLong(),
        reportSha256 = document.controlString("reportSha256"),
        configurationSha256 = document.controlObject("oracle").controlString("configurationSha256"),
        actionsSha256 = actions.actionsSha256,
        captureContextSha256 = predecessors.context.captureContextSha256,
        headerManifestSha256 = document.controlObject("commitments")
            .controlString("canonicalCaptureHeaderCandidateManifestSha256"),
        actions = actions.actions,
        headerPaths = predecessors.context.headerPaths,
        sourceOnlyUnits = predecessors.context.sourceOnlyUnits,
        baseEnvironment = predecessors.context.baseEnvironment,
        blockerCodes = CAPTURE_BLOCKERS.map { it.controlString("code") },
        canonicalBytes = bytes.copyOf(),
    )

    /** Private raw-path constructor; no caller-created registry or parsed-object seam exists. */
    private class ValidatedCaptureInputRegistry private constructor(
        paths: CaptureInputPaths,
        limits: FullTreeClangCaptureInputLimits,
    ) : FullTreeClangCaptureInputRegistry {
        private val state = authenticate(paths, limits)

        override val artifactSha256: String = state.artifactSha256
        override val artifactBytes: Long = state.artifactBytes
        override val reportSha256: String = state.reportSha256
        override val configurationSha256: String = state.configurationSha256
        override val captureContextSha256: String = state.captureContextSha256
        override val captureActionsSha256: String = state.actionsSha256
        override val canonicalCaptureHeaderCandidateManifestSha256: String = state.headerManifestSha256
        override val actions: List<FullTreeClangCaptureAction> = Collections.unmodifiableList(
            ArrayList(state.actions),
        )
        override val canonicalCaptureHeaderCandidatePaths: List<String> = Collections.unmodifiableList(
            ArrayList(state.headerPaths),
        )
        override val sourceOnlyUnits: List<FullTreePlanningSourceOnlyUnit> = Collections.unmodifiableList(
            ArrayList(state.sourceOnlyUnits),
        )
        override val baseEnvironment: Map<String, String> = Collections.unmodifiableMap(
            LinkedHashMap(state.baseEnvironment),
        )
        override val blockerCodes: List<String> = Collections.unmodifiableList(ArrayList(state.blockerCodes))
        private val storedCanonicalBytes = state.canonicalBytes.copyOf()
        override val canonicalBytes: ByteArray
            get() = storedCanonicalBytes.copyOf()
        private val actionsByOwner: Map<String, FullTreeClangCaptureAction> = Collections.unmodifiableMap(
            LinkedHashMap<String, FullTreeClangCaptureAction>().apply {
                actions.forEach { action ->
                    if (action.moduleId != action.unitId || put(action.unitId, action) != null) {
                        captureFail("capture registry contains an invalid owner-module action identity")
                    }
                }
            },
        )

        override fun requireActionForOwnerModule(ownerUnitId: String): FullTreeClangCaptureAction {
            if (!ownerUnitId.matches(CAPTURE_COMPILATION_UNIT_ID)) {
                captureFail("capture action owner ID is invalid")
            }
            return actionsByOwner[ownerUnitId]
                ?: captureFail("capture action owner is outside the authenticated A13 population")
        }

        companion object {
            fun load(
                paths: CaptureInputPaths,
                limits: FullTreeClangCaptureInputLimits,
            ): FullTreeClangCaptureInputRegistry = ValidatedCaptureInputRegistry(paths, limits)
        }
    }
}

private data class CaptureInputPaths(
    val artifact: Path,
    val readiness: Path,
    val generatedInventory: Path,
    val sourceArchive: Path,
    val generatedArchive: Path,
    val generatedProvenance: Path,
    val scope: Path,
    val sourceLock: Path,
    val artifactManifest: Path,
    val buildRecord: Path,
    val inventory: Path,
    val sourceInventory: Path,
    val planningInventory: Path,
) {
    fun all(): List<Path> = listOf(
        artifact,
        readiness,
        generatedInventory,
        sourceArchive,
        generatedArchive,
        generatedProvenance,
        scope,
        sourceLock,
        artifactManifest,
        buildRecord,
        inventory,
        sourceInventory,
        planningInventory,
    )
}

private data class CapturePredecessors(
    val readiness: AuthenticatedFullTreeHeaderPlanReadiness,
    val generated: FullTreeGeneratedFileRegistry,
    val context: CaptureExpectedContext,
)

private data class CaptureExpectedContext(
    val planningDocument: JsonObject,
    val buildRecord: JsonObject,
    val buildRecordSha256: String,
    val generatedInventoryDocument: JsonObject,
    val oracleDocument: JsonObject,
    val sourceDocument: JsonObject,
    val generatedDocument: JsonObject,
    val compilerDocument: JsonObject,
    val buildDocument: JsonObject,
    val environmentDocument: JsonObject,
    val baseEnvironment: Map<String, String>,
    val baseEnvironmentSha256: String,
    val environmentBytes: Long,
    val captureContextSha256: String,
    val headerManifestSha256: String,
    val buildRoot: String,
    val cDriver: String,
    val cxxDriver: String,
    val sourceArchiveSha256: String,
    val modules: List<CaptureModule>,
    val sourceOnlyUnits: List<FullTreePlanningSourceOnlyUnit>,
    val sourceHeaderCount: Int,
    val generatedHeaderCount: Int,
    val headerPaths: List<String>,
    val headerPathBytes: Long,
    val generatedTranslationUnits: Map<String, FullTreeGeneratedTranslationUnit>,
)

private data class CaptureModule(
    val moduleId: String,
    val unitId: String,
    val shardId: String,
    val sourceKind: String,
    val sourcePath: String,
    val mainInput: String,
)

private data class CaptureEnvironment(
    val document: JsonObject,
    val variables: Map<String, String>,
    val sha256: String,
    val bytes: Long,
)

private data class ValidatedCaptureActions(
    val documents: List<JsonObject>,
    val actions: List<ValidatedClangCaptureAction>,
    val actionsSha256: String,
    val argumentCount: Long,
    val argumentBytes: Long,
    val actionPathBytes: Long,
)

private data class ValidatedClangCaptureAction(
    override val actionSha256: String,
    override val moduleId: String,
    override val unitId: String,
    override val shardId: String,
    override val sourceKind: String,
    override val sourcePath: String,
    override val workingDirectory: String,
    override val mainInput: String,
    override val arguments: List<String>,
    override val objectOutput: String,
    override val dependencyFile: String,
    override val traceArtifactPath: String,
) : FullTreeClangCaptureAction

private data class ValidatedCaptureInputState(
    val artifactSha256: String,
    val artifactBytes: Long,
    val reportSha256: String,
    val configurationSha256: String,
    val captureContextSha256: String,
    val actionsSha256: String,
    val headerManifestSha256: String,
    val actions: List<ValidatedClangCaptureAction>,
    val headerPaths: List<String>,
    val sourceOnlyUnits: List<FullTreePlanningSourceOnlyUnit>,
    val baseEnvironment: Map<String, String>,
    val blockerCodes: List<String>,
    val canonicalBytes: ByteArray,
)

private data class CapturePredecessorSnapshot(
    val readinessArtifactSha256: String,
    val readinessReportSha256: String,
    val readinessConfigurationSha256: String,
    val generatedArtifactSha256: String,
    val generatedReportSha256: String,
    val generatedConfigurationSha256: String,
    val planningDocument: JsonObject,
    val buildRecord: JsonObject,
    val generatedInventoryDocument: JsonObject,
    val modules: List<CaptureModule>,
    val sourceOnly: List<CaptureSourceOnlySnapshot>,
    val headerPaths: List<String>,
    val generatedFiles: List<CaptureGeneratedFileSnapshot>,
    val staticDocuments: List<JsonObject>,
)

private data class CaptureSourceOnlySnapshot(
    val sourcePath: String,
    val shardId: String,
    val reasonCode: String,
)

private data class CaptureGeneratedFileSnapshot(
    val sourcePath: String,
    val bytes: Long,
    val sha256: String,
    val actionSha256: String,
    val moduleId: String?,
    val unitId: String?,
    val shardId: String?,
)

private fun capturePredecessorSnapshot(value: CapturePredecessors): CapturePredecessorSnapshot {
    val context = value.context
    return CapturePredecessorSnapshot(
        readinessArtifactSha256 = value.readiness.artifactSha256,
        readinessReportSha256 = value.readiness.reportSha256,
        readinessConfigurationSha256 = value.readiness.configurationSha256,
        generatedArtifactSha256 = value.generated.artifactSha256,
        generatedReportSha256 = value.generated.reportSha256,
        generatedConfigurationSha256 = value.generated.configurationSha256,
        planningDocument = context.planningDocument,
        buildRecord = context.buildRecord,
        generatedInventoryDocument = context.generatedInventoryDocument,
        modules = context.modules,
        sourceOnly = context.sourceOnlyUnits.map { unit ->
            CaptureSourceOnlySnapshot(unit.sourcePath, unit.shardId, unit.reasonCode)
        },
        headerPaths = context.headerPaths,
        generatedFiles = value.generated.generatedFiles.map { file ->
            val unit = file as? FullTreeGeneratedTranslationUnit
            CaptureGeneratedFileSnapshot(
                file.sourcePath,
                file.bytes,
                file.sha256,
                file.generatorActionSha256,
                unit?.moduleId,
                unit?.unitId,
                unit?.shardId,
            )
        },
        staticDocuments = listOf(
            context.oracleDocument,
            context.sourceDocument,
            context.generatedDocument,
            context.compilerDocument,
            context.buildDocument,
            context.environmentDocument,
        ),
    )
}

private fun readStableCaptureObject(
    file: StableControlFile,
    limits: FullTreeClangCaptureInputLimits,
): Pair<JsonObject, ByteArray> {
    if (file.size !in 1L..limits.maximumCanonicalBytes.toLong()) {
        captureFail("full-tree Clang capture input exceeds its byte bound")
    }
    val bytes = file.readExactly(0L, file.size.toInt(), "full-tree Clang capture input")
    val document = try {
        OracleJson.parseCanonical(bytes, controlJsonLimits(limits.maximumCanonicalBytes)) as? JsonObject
            ?: captureFail("full-tree Clang capture input root must be an object")
    } catch (failure: FullTreeControlException) {
        throw failure
    } catch (failure: Exception) {
        throw FullTreeControlException("full-tree Clang capture input is not strict canonical JSON", failure)
    }
    try {
        OracleSchemas.validate(CAPTURE_SCHEMA, document)
    } catch (failure: Exception) {
        throw FullTreeControlException("full-tree Clang capture input fails its bundled schema", failure)
    }
    return document to bytes
}

private fun validateCaptureReportHash(document: JsonObject, maximumBytes: Int) {
    val withoutHash = JsonObject(document.filterKeys { it != "reportSha256" })
    val expected = OracleArtifacts.sha256(
        OracleJson.canonicalBytes(withoutHash, controlJsonLimits(maximumBytes)),
    )
    if (document.controlString("reportSha256") != expected) {
        captureFail("full-tree Clang capture input report hash does not reconcile")
    }
}

private fun requireDistinctCaptureInputs(paths: CaptureInputPaths) {
    val normalized = paths.all().map { it.toAbsolutePath().normalize() }
    if (normalized.toSet().size != normalized.size) {
        captureFail("Clang capture input paths must be distinct")
    }
    val identities = HashSet<Any>()
    normalized.forEach { path ->
        val attributes = try {
            Files.readAttributes(path, BasicFileAttributes::class.java, LinkOption.NOFOLLOW_LINKS)
        } catch (failure: Exception) {
            throw FullTreeControlException("Clang capture input is unavailable", failure)
        }
        if (!attributes.isRegularFile || attributes.isSymbolicLink || attributes.fileKey() == null) {
            captureFail("Clang capture input path is not an identified regular file")
        }
        if (!identities.add(attributes.fileKey())) {
            captureFail("Clang capture inputs contain a physical-file alias")
        }
    }
}

private fun requireCaptureAbsolutePath(
    value: String,
    label: String,
    limits: FullTreeClangCaptureInputLimits,
): String {
    val bytes = value.toByteArray(StandardCharsets.UTF_8)
    if (!value.startsWith('/') || value == "/" || value.endsWith('/') || value.contains("//") ||
        value.any { it == '\u0000' || it == '\r' || it == '\n' || it == '\\' } ||
        bytes.size > limits.maximumPathBytes
    ) {
        captureFail("$label is not a canonical absolute path")
    }
    value.removePrefix("/").split('/').forEach { component ->
        if (component.isEmpty() || component == "." || component == ".." ||
            component.toByteArray(StandardCharsets.UTF_8).size > limits.maximumPathComponentBytes
        ) {
            captureFail("$label contains a noncanonical path component")
        }
    }
    return value
}

private fun requireCaptureRelativePath(
    value: String,
    label: String,
    limits: FullTreeClangCaptureInputLimits,
): String {
    val bytes = value.toByteArray(StandardCharsets.UTF_8)
    if (value.isEmpty() || value.startsWith('/') || value.endsWith('/') || value.contains("//") ||
        value.any { it == '\u0000' || it == '\r' || it == '\n' || it == '\\' } ||
        bytes.size > limits.maximumPathBytes
    ) {
        captureFail("$label is not a canonical relative path")
    }
    value.split('/').forEach { component ->
        if (component.isEmpty() || component == "." || component == ".." ||
            component.toByteArray(StandardCharsets.UTF_8).size > limits.maximumPathComponentBytes
        ) {
            captureFail("$label contains a noncanonical path component")
        }
    }
    return value
}

private fun requireCaptureHeaderCandidatePath(
    path: String,
    limits: FullTreeClangCaptureInputLimits,
) {
    val prefix = when {
        path.startsWith("source/") -> "source/"
        path.startsWith("generated/") -> "generated/"
        else -> captureFail("capture header candidate is outside source/generated namespaces")
    }
    requireCaptureRelativePath(path.removePrefix(prefix), "capture header candidate", limits)
    if (!CAPTURE_HEADER_SUFFIXES.any(path::endsWith)) {
        captureFail("capture header candidate has an ineligible case-sensitive suffix")
    }
}

private fun requireDisjointCaptureRoots(vararg roots: String) {
    roots.indices.forEach { leftIndex ->
        roots.indices.filter { it > leftIndex }.forEach { rightIndex ->
            val left = roots[leftIndex]
            val right = roots[rightIndex]
            if (left == right || left.startsWith("$right/") || right.startsWith("$left/")) {
                captureFail("capture physical root namespaces are equal or nested")
            }
        }
    }
}

private fun captureAddExact(left: Long, right: Long, label: String): Long = try {
    Math.addExact(left, right)
} catch (failure: ArithmeticException) {
    throw FullTreeControlException("$label count overflows", failure)
}

private fun captureMultiplyExact(left: Long, right: Long, label: String): Long = try {
    Math.multiplyExact(left, right)
} catch (failure: ArithmeticException) {
    throw FullTreeControlException("$label count overflows", failure)
}

private fun captureFail(message: String): Nothing = throw FullTreeControlException(message)

private fun ByteArray.captureHex(): String = joinToString("") { byte ->
    (byte.toInt() and 0xff).toString(16).padStart(2, '0')
}

private fun captureCanonicalCommitment(domain: String, value: JsonObject): String =
    CaptureCommitment(domain).apply {
        token(
            OracleJson.canonicalBytes(
                value,
                controlJsonLimits(CAPTURE_MAXIMUM_CANONICAL_BYTES),
            ),
        )
    }.finish()

private fun captureCanonicalCommitment(domain: String, value: JsonArray): String =
    CaptureCommitment(domain).apply {
        token(
            OracleJson.canonicalBytes(
                value,
                controlJsonLimits(CAPTURE_MAXIMUM_CANONICAL_BYTES),
            ),
        )
    }.finish()

private fun captureContextDocument(
    oracle: JsonObject,
    source: JsonObject,
    generated: JsonObject,
    compiler: JsonObject,
    build: JsonObject,
    environment: JsonObject,
    headerManifestSha256: String,
): JsonObject = JsonObject(
    mapOf(
        "build" to build,
        "canonicalCaptureHeaderCandidateManifestSha256" to JsonPrimitive(headerManifestSha256),
        "compiler" to compiler,
        "environment" to environment,
        "generated" to generated,
        "oracle" to oracle,
        "source" to source,
    ),
)

private class CaptureCommitment(domain: String) {
    private val digest = MessageDigest.getInstance("SHA-256")

    init {
        token(domain.toByteArray(StandardCharsets.UTF_8))
    }

    fun long(value: Long) {
        digest.update(ByteBuffer.allocate(Long.SIZE_BYTES).order(ByteOrder.BIG_ENDIAN).putLong(value).array())
    }

    fun token(bytes: ByteArray) {
        long(bytes.size.toLong())
        digest.update(bytes)
    }

    fun finish(): String = digest.digest().captureHex()
}

private val CAPTURE_AUTHORITY = JsonObject(
    mapOf(
        "a13ModuleActionJoinExact" to JsonPrimitive(true),
        "captureInputAuthenticated" to JsonPrimitive(false),
        "captureOutputsPresent" to JsonPrimitive(false),
        "captureStarted" to JsonPrimitive(false),
        "cleanCompilationProven" to JsonPrimitive(false),
        "compilerActionsAuthenticated" to JsonPrimitive(false),
        "compilerCaptureAuthenticated" to JsonPrimitive(false),
        "compilerOptionArityValidated" to JsonPrimitive(false),
        "compilerWriteSetContained" to JsonPrimitive(false),
        "exitStatusesPresent" to JsonPrimitive(false),
        "headerPlanReady" to JsonPrimitive(false),
        "headerPopulationComplete" to JsonPrimitive(false),
        "predecessorBindingsReconciled" to JsonPrimitive(true),
        "releaseEligible" to JsonPrimitive(false),
        "sourceAndGeneratedHeaderCandidatesCombined" to JsonPrimitive(true),
        "status" to JsonPrimitive("unexecuted-unreceipted-capture-input"),
    ),
)

private val CAPTURE_ACP_BOUNDARY = JsonObject(
    mapOf(
        "candidateAdmissionOwner" to JsonPrimitive("kotlin-jvm-host"),
        "candidateContribution" to JsonPrimitive("authenticated-session-change-build-artifact-provenance"),
        "candidateEvidenceDisposition" to JsonPrimitive("non-authoritative-input-to-later-host-validation"),
        "candidateLineageAdmission" to JsonPrimitive("not-an-input-to-clang-capture-input-v1"),
        "candidateLiveExecutionOwner" to JsonPrimitive("separately-reviewed-kotlin-jvm-host"),
        "candidateProvenanceAccess" to JsonPrimitive("read-only-oracle-input"),
        "captureAuthority" to JsonPrimitive(false),
        "captureInputAuthoringAuthority" to JsonPrimitive(false),
        "certificationAuthority" to JsonPrimitive(false),
        "compilerActionAuthoringAuthority" to JsonPrimitive(false),
        "containmentAuthority" to JsonPrimitive(false),
        "executionAuthority" to JsonPrimitive(false),
        "observationAuthoringAuthority" to JsonPrimitive(false),
        "oracleAuthority" to JsonPrimitive(false),
        "policyAuthoringAuthority" to JsonPrimitive(false),
        "referenceAuthoringAuthority" to JsonPrimitive(false),
        "referenceSubjectAdmission" to JsonPrimitive("kotlin-jvm-host-only"),
        "releaseAuthority" to JsonPrimitive(false),
        "role" to JsonPrimitive("first-class-candidate-producer-operator"),
        "scoringAuthority" to JsonPrimitive(false),
        "startAuthority" to JsonPrimitive(false),
        "terminalAbsenceAuthority" to JsonPrimitive(false),
        "validationAuthority" to JsonPrimitive(false),
    ),
)

private val CAPTURE_POLICY = JsonObject(
    mapOf(
        "actionCoverage" to JsonPrimitive("exact-one-per-authenticated-a13-module"),
        "actionIdentity" to JsonPrimitive(
            "kotlin-jvm-derived-from-global-predecessor-context-and-complete-explicit-argv-environment-bindings",
        ),
        "actionOrdering" to JsonPrimitive("authenticated-a13-source-module-order"),
        "argumentFraming" to JsonPrimitive(
            "fixed-driver-config-dependency-output-compile-main-frame-plus-dash-prefixed-token-tail",
        ),
        "argumentTransport" to JsonPrimitive(
            "ordered-execve-argv-no-shell-no-response-or-compiler-config-files",
        ),
        "commandMutation" to JsonPrimitive("forbidden"),
        "compilerWriteSetDisposition" to JsonPrimitive(
            "not-proven-requires-isolated-runner-containment",
        ),
        "executionDisposition" to JsonPrimitive("not-executed"),
        "headerFiltering" to JsonPrimitive("direct-per-file"),
        "headerOutputFormat" to JsonPrimitive("json-v2.0.0"),
        "outputRecordModel" to JsonPrimitive(
            "actions-plus-header-candidates-plus-source-only-plus-base-environment-plus-eight-blockers",
        ),
        "tailOptionArityDisposition" to JsonPrimitive(
            "unvalidated-requires-reviewed-option-profile-before-execution",
        ),
        "traceSlot" to JsonPrimitive("traces/<derived-action-sha256>.json"),
        "workUnitModel" to JsonPrimitive(
            "64-plus-12-per-action-plus-4-per-argument-plus-3-per-header-plus-2-per-source-only-" +
            "plus-2-per-base-environment-plus-2-per-blocker",
        ),
        "zeroByteTraceDisposition" to JsonPrimitive("present-empty-not-missing"),
    ),
)

private val CAPTURE_BOUNDS = JsonObject(
    mapOf(
        "maximumActionPathBytes" to JsonPrimitive(CAPTURE_MAXIMUM_ACTION_PATH_BYTES),
        "maximumActions" to JsonPrimitive(CAPTURE_MAXIMUM_ACTIONS),
        "maximumArgumentBytes" to JsonPrimitive(CAPTURE_MAXIMUM_ARGUMENT_BYTES),
        "maximumArgumentsPerAction" to JsonPrimitive(CAPTURE_MAXIMUM_ARGUMENTS_PER_ACTION),
        "maximumBaseEnvironmentVariables" to JsonPrimitive(CAPTURE_MAXIMUM_BASE_ENVIRONMENT_VARIABLES),
        "maximumBlockers" to JsonPrimitive(8),
        "maximumCanonicalBytes" to JsonPrimitive(CAPTURE_MAXIMUM_CANONICAL_BYTES),
        "maximumCaptureHeaderCandidates" to JsonPrimitive(CAPTURE_MAXIMUM_HEADER_CANDIDATES),
        "maximumCompilerBytes" to JsonPrimitive(CAPTURE_MAXIMUM_COMPILER_BYTES),
        "maximumEnvironmentBytes" to JsonPrimitive(CAPTURE_MAXIMUM_ENVIRONMENT_BYTES),
        "maximumHeaderPathBytes" to JsonPrimitive(CAPTURE_MAXIMUM_HEADER_PATH_BYTES),
        "maximumOutputRecords" to JsonPrimitive(CAPTURE_MAXIMUM_OUTPUT_RECORDS),
        "maximumPathBytes" to JsonPrimitive(CAPTURE_MAXIMUM_PATH_BYTES),
        "maximumPathComponentBytes" to JsonPrimitive(CAPTURE_MAXIMUM_PATH_COMPONENT_BYTES),
        "maximumSourceOnlyUnits" to JsonPrimitive(CAPTURE_MAXIMUM_SOURCE_ONLY_UNITS),
        "maximumTotalArgumentBytes" to JsonPrimitive(CAPTURE_MAXIMUM_TOTAL_ARGUMENT_BYTES),
        "maximumTotalArguments" to JsonPrimitive(CAPTURE_MAXIMUM_TOTAL_ARGUMENTS),
        "maximumWorkUnits" to JsonPrimitive(CAPTURE_MAXIMUM_WORK_UNITS),
    ),
)

private val CAPTURE_FIXED_ENVIRONMENT = JsonArray(
    listOf(
        JsonObject(
            mapOf(
                "name" to JsonPrimitive("CC_PRINT_HEADERS_FILTERING"),
                "value" to JsonPrimitive("direct-per-file"),
            ),
        ),
        JsonObject(
            mapOf(
                "name" to JsonPrimitive("CC_PRINT_HEADERS_FORMAT"),
                "value" to JsonPrimitive("json"),
            ),
        ),
    ),
)

private val CAPTURE_PER_ACTION_ENVIRONMENT = JsonObject(
    mapOf(
        "name" to JsonPrimitive("CC_PRINT_HEADERS_FILE"),
        "valueSource" to JsonPrimitive("trusted-scratch-root-plus-derived-trace-slot"),
    ),
)

private val CAPTURE_BLOCKER_DISPOSITIONS = listOf(
    captureBlockerDisposition(
        "header-plan-readiness-v1",
        "complete-project-header-inventory-missing",
        "carried",
        "complete-project-header-inventory-missing",
    ),
    captureBlockerDisposition(
        "header-plan-readiness-v1",
        "compiler-capture-provenance-missing",
        "carried",
        "compiler-capture-provenance-missing",
    ),
    captureBlockerDisposition(
        "header-plan-readiness-v1",
        "generated-file-provenance-missing",
        "refined-by-generated-registry",
        "generated-generation-receipt-missing",
        "generated-snapshot-completeness-unproven",
    ),
    captureBlockerDisposition(
        "header-plan-readiness-v1",
        "ninja-generator-provenance-missing",
        "refined-by-generated-registry",
        "ninja-live-edge-replay-missing",
    ),
    captureBlockerDisposition(
        "header-plan-readiness-v1",
        "physical-project-roots-unverified",
        "carried",
        "physical-project-roots-unverified",
    ),
    captureBlockerDisposition(
        "generated-file-inventory-v1",
        "generated-generation-receipt-missing",
        "carried",
        "generated-generation-receipt-missing",
    ),
    captureBlockerDisposition(
        "generated-file-inventory-v1",
        "generated-snapshot-completeness-unproven",
        "carried",
        "generated-snapshot-completeness-unproven",
    ),
    captureBlockerDisposition(
        "generated-file-inventory-v1",
        "ninja-live-edge-replay-missing",
        "carried",
        "ninja-live-edge-replay-missing",
    ),
    captureBlockerDisposition(
        "generated-file-inventory-v1",
        "physical-build-root-unverified",
        "carried",
        "physical-build-root-unverified",
    ),
    captureBlockerDisposition(
        "clang-capture-input-v1",
        "compiler-option-arity-unvalidated",
        "introduced",
        "compiler-option-arity-unvalidated",
    ),
)

private val CAPTURE_BLOCKERS = listOf(
    captureBlocker("complete-project-header-inventory-missing"),
    captureBlocker("compiler-capture-provenance-missing"),
    captureBlocker("compiler-option-arity-unvalidated"),
    captureBlocker("generated-generation-receipt-missing"),
    captureBlocker("generated-snapshot-completeness-unproven"),
    captureBlocker("ninja-live-edge-replay-missing"),
    captureBlocker("physical-build-root-unverified"),
    captureBlocker("physical-project-roots-unverified"),
)

private fun captureBlocker(code: String): JsonObject = JsonObject(
    mapOf("code" to JsonPrimitive(code), "status" to JsonPrimitive("unresolved")),
)

private fun captureBlockerDisposition(
    source: String,
    code: String,
    disposition: String,
    vararg activeCodes: String,
): JsonObject = JsonObject(
    mapOf(
        "activeCodes" to JsonArray(activeCodes.map(::JsonPrimitive)),
        "code" to JsonPrimitive(code),
        "disposition" to JsonPrimitive(disposition),
        "source" to JsonPrimitive(source),
    ),
)

private val CAPTURE_CONFIGURATION_POLICY = JsonObject(
    mapOf(
        "acpBoundary" to CAPTURE_ACP_BOUNDARY,
        "authority" to CAPTURE_AUTHORITY,
        "bounds" to CAPTURE_BOUNDS,
        "capturePolicy" to CAPTURE_POLICY,
        "generatedInventorySchemaSha256" to JsonPrimitive(
            OracleSchemas.identity("full-tree-generated-file-inventory").sha256,
        ),
        "headerReadinessSchemaSha256" to JsonPrimitive(
            OracleSchemas.identity("full-tree-header-plan-readiness").sha256,
        ),
        "id" to JsonPrimitive(CAPTURE_SCHEMA),
        "version" to JsonPrimitive(1),
    ),
)

private val CAPTURE_ENVIRONMENT_NAME = Regex("[A-Z_][A-Z0-9_]*")
private val CAPTURE_COMPILATION_UNIT_ID = Regex("cu-[0-9a-f]{32}")
private val CAPTURE_HEADER_SUFFIXES = listOf(".def", ".h", ".hh", ".hpp", ".hxx", ".inc")
private val CAPTURE_OPAQUE_FORWARDING_PREFIXES = listOf("-Wa,", "-Wl,", "-Wp,", "-X", "-mllvm")
private val CAPTURE_FORBIDDEN_ENVIRONMENT_PREFIXES = listOf("CC_PRINT_HEADERS", "CLANG_CONFIG")
private val CAPTURE_FORBIDDEN_ENVIRONMENT_NAMES = setOf(
    "CCC_OVERRIDE_OPTIONS",
    "QA_OVERRIDE_GCC3_OPTIONS",
)
private val CAPTURE_FORBIDDEN_ARGUMENTS = setOf(
    "-",
    "--",
    "-cc1",
    "-cc1as",
    "-E",
    "-S",
    "-fno-integrated-as",
    "-fsyntax-only",
    "-M",
    "-MM",
    "-MMD",
)
private val CAPTURE_CAPTURE_OPTION_PREFIXES = listOf(
    "-header-include-file",
    "-header-include-filtering",
    "-header-include-format",
)

private const val CAPTURE_SCHEMA = "full-tree-clang-capture-input"
private const val CAPTURE_COMPILE_FRAME_SIZE = 11
private const val CAPTURE_COMPILER_IDENTITY_DOMAIN = "full-tree-clang-capture-compiler-identity-v1"
private const val CAPTURE_ENVIRONMENT_DOMAIN = "full-tree-clang-capture-base-environment-v1"
private const val CAPTURE_CONTEXT_DOMAIN = "full-tree-clang-capture-global-context-v1"
private const val CAPTURE_ACTION_DOMAIN = "full-tree-clang-capture-action-v2"
private const val CAPTURE_ACTION_MANIFEST_DOMAIN = "full-tree-clang-capture-action-manifest-v1"
private const val CAPTURE_HEADER_MANIFEST_DOMAIN = "full-tree-clang-capture-header-candidate-manifest-v1"
private const val CAPTURE_MAXIMUM_ACTIONS = 10_000
private const val CAPTURE_MAXIMUM_ACTION_PATH_BYTES = 16L * 1024L * 1024L
private const val CAPTURE_MAXIMUM_ARGUMENT_BYTES = 16 * 1024
private const val CAPTURE_MAXIMUM_ARGUMENTS_PER_ACTION = 4096
private const val CAPTURE_MAXIMUM_BASE_ENVIRONMENT_VARIABLES = 256
private const val CAPTURE_MAXIMUM_CANONICAL_BYTES = 64 * 1024 * 1024
private const val CAPTURE_MAXIMUM_HEADER_CANDIDATES = 100_000
private const val CAPTURE_MAXIMUM_COMPILER_BYTES = 512L * 1024L * 1024L
private const val CAPTURE_MAXIMUM_ENVIRONMENT_BYTES = 4L * 1024L * 1024L
private const val CAPTURE_MAXIMUM_HEADER_PATH_BYTES = 16L * 1024L * 1024L
private const val CAPTURE_MAXIMUM_OUTPUT_RECORDS = 160_264L
private const val CAPTURE_MAXIMUM_PATH_BYTES = 4096
private const val CAPTURE_MAXIMUM_PATH_COMPONENT_BYTES = 255
private const val CAPTURE_MAXIMUM_SOURCE_ONLY_UNITS = 50_000
private const val CAPTURE_MAXIMUM_TOTAL_ARGUMENT_BYTES = 32L * 1024L * 1024L
private const val CAPTURE_MAXIMUM_TOTAL_ARGUMENTS = 500_000L
private const val CAPTURE_MAXIMUM_WORK_UNITS = 5_000_000L
